apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
type: Opaque
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:Z19M63Fy5nfMsel3wsUunFlGkk35an3Zpu8gbyuo7gJGf4xCRoCSQIatE/Lltd2uw4iaP76Wx7+QoK5cBBNyeKCF+9hW5o2ODMXo3ytWP2A=,iv:p6iq1lmuU9ZowkUgDe5arY6NJHuLfuEcl0RAFlqcZB8=,tag:f5vB4yhyDzCBBKAsHGosKQ==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:rxG9CZhcECt1nWh685fFq7+7EUX0U4QD7wrBEc8ZkPvg/F3kCnV3PmOAkqYSrQGO1rKPf11rte7FpeftsdMV,iv:M9YUn6F6oBYs7HthNXmb5Cj38LZhrKJN+uGzrn79GIA=,tag:kXv8KCTj9WAFjxQITjmfJw==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:K737v6jKPlD51S5ZxWhqBt+2S+XhmLMIGOjF8Jyweq0=,iv:/4xqjlTqCQTfRybZmZdRaVcAXhis821bO4AUmbVWbrQ=,tag:jpOPfgWsgzbkb3SGrRpm4g==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:gwAnUJtiJQAiJG6iH0G/rdAGuGm6w1YsHeGwS5YFqQxZqn2S3slOHRMyDl6g0zBWtnsfwQyaQVncchZBd0iyJg==,iv:9GG/dRcn8LC4jIzi77K0axioAei+bwfaW+/8r9B451s=,tag:lnnsT6KYb64SI1vSsHcpOQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-06-29T23:18:53Z"
    mac: ENC[AES256_GCM,data:ME5cELcnVA032JdBARKqP49B9ZW+o5XE/I4LrloeY2USolSlaT3IQzdexc2mRL6nMCFvJbcjn9r8iBRcIimKLDczphUrTOSsCRvum3tEL/HbqNpq0L7bSD2ibjMZSUhnAVFoLhO4Fm2IiIwWl65qIpEY6NRvYfxGp5TvE6klgYE=,iv:YS34xmYS2gwiH7WJnk1aRkXZjYcz5bfva1KYcPBkZtI=,tag:uTP30E+31ByNBQjj/nrVbQ==,type:str]
    pgp:
        - created_at: "2024-06-29T23:18:53Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA4ZC/5oeS6LPAQ/+Ks2XodWCgb/1vuz70B+sdsl2QAeNl3dn8tE9DZgt5fLL
            w0sBFmshDV+SkdSKyKm2Un9XelZmujxuYNi38kb2dkGVm5Al205ATNB/2s+f08Oq
            Q+EADQuaonBP/NpoL46d8cxP7iowIIrIC4rLT/u2ELES5lLsHsykYI0OdpU3aqaA
            JWAKXwdrytIU/1q3zB52UuZCkoJWAtYsy5AXREr1bl508q0afzgNbgbyPia4WnIy
            LPCJjGLuna+qX11YxB2amCxoUwRKODi6CdvbNouyfb5dqwYMz2IzubE12IktLqq2
            L+94aPpQTa56Lv+Y4mSQ6ByGmT9cBFaync9VQ/NMIhJXFhmlL6/+jxSfUMZxIvlg
            14YhZ1B6pZklC1dxkVip3nubRz8O0C69+vC+1wKhKIR4KVk6BHPBxdbv25uqBZty
            nhGclDYHCHV5Iui0laAp6cNYg+DR6MmHHwqSop6QuXs0DHpicm6yQQb0Yj7Ih4tn
            bpuPRKMUQKd4ExD65UuF5WVZU5q1dCj/PRfZwzOxfG/00uy/+5OHrvom7UdxSffa
            VQlQij1rsiP1NdrU4fPRWMJzI7XR9z3sitZ8lvcJsHJ7/IflnV0erU9Kor2L3z1x
            4UZ0ovPqoGfPoPdd0K2ge/kaqvxm09db/rkf9BXWvtpIGUn7Y6WGHah/+Eekn/fU
            aAEJAhBvQQoZNAYPEwyHE2lSXCCKl0i7sKIcrXKh9w5zQKGMO3+uwRuWn9uK9tAY
            EGf0o4PGQwuHbHEgd1L4HIwvBnir5ofrVUb9Ca0Yk7iVGTtHAlyXkSfxzdBLujSf
            lYKz4Xh5qiWG
            =QBsS
            -----END PGP MESSAGE-----
          fp: CC3248CD7FFAD043BD8C51B3E5690E38FAF86EEB
        - created_at: "2024-06-29T23:18:53Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DHfhkqE7LHSASAQdAMx7iWTUG+ZWqGzmBds5P56h9ZcOSuS7XC8z/q4RMNDIw
            ZRQctXUIssOI/JNAophydKpTfmb9eo5fXuA6+VaecRubIIAGzR/pdtitcOes4drt
            1GgBCQIQhsLYTe2Kot8owipJniw5xOPQMxrVW5mT2ZqfS+5vpNw7pRvadPoYTz1/
            7+v5tS6IQJPMJKRtK0KWWf8FgsuVCcCqVLgzs5NVLTv7bRu4V3YnVsJdlCBCd54X
            ElbJgXCEWouuRA==
            =XoQv
            -----END PGP MESSAGE-----
          fp: E39A9ADC5719F27F46267014C7339B5CD6A9FAB1
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
