apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
type: Opaque
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:uz03uki7abFQmpxQHNjYpXaczDGG2lzmXRlm/z48M6Co/QO6sO58+I4BEWKlmDDU2IhqBQMSZ262APgyK9LBQ67ggGT6evf0yviCjA1Filo=,iv:Ekuo6nsrvDu5F8MQwP4/EO4PaKYBSZ5Y377bAyJuf9I=,tag:mSyDX+V4Bc431yzdQn4P3Q==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:YoQ66n4FTS1rcR0CdUCtw2nj9BraZ4DrTDzY8daOGhVWOQg8WtiZmkWtpzE1p4NvrLZZtwddyMq4TssX4Mbx,iv:sJwKwDZFzNPLpbS/m/LCpAF3N4sDBTbykov9gOZtFiE=,tag:0tnBeVbyPsFfIgaaHY//og==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:Fwe+bOaMehMqX2TXPnCuRjJXlsiUK+nO3fawT3SwlZ8=,iv:WE1ET5v7eWyxAdfGXawwkJ1J820jN6X/Vd4H9U//6+Y=,tag:RZqv7f29F4NF16OyrIYsdQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:aDfdCDQ577tjaHrRDE8VHS6m5GoRzPE3+a2tyDwxXh/3mbvJR80wd3xXYC8fbsVaHFAcM4Oy6JANfaAgXFr6rw==,iv:8UHjOv2skzcl3/YZ3b0iAyCvSkQjCrne7VsUkytL3Xk=,tag:605h1EpO5781g2nKubgqUw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-06-29T23:29:20Z"
    mac: ENC[AES256_GCM,data:jM837cNTVfDsv1pIucLM32NT6YSkSdfhG3dIe/7RqciKlbd80plpjf7duR/63FWw39gBMfp70kuyZiu3EDFF+5LkeIw7w3MCWRvhgmQ+pv88tsinnp6W5BlkyXeGcHMRZhOTMHEI+nsddQMacTFd0iyC2DHi5JGx2g+LpAjg4iM=,iv:gbz67GFsYE+ePaZmI12NSHwIqIiXdtT8dYjj+jrUZ9M=,tag:LT4qA4DCRpMdz2xOgFrhKw==,type:str]
    pgp:
        - created_at: "2024-06-29T23:29:20Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA4ZC/5oeS6LPARAAmnYU9vOX0Ey6LUyZxexTYZ+nZfWl8uwR/Fdjszyi0D0E
            RZzZNekxh/ADyOjneruykEs4kVxH+8IrBMEwQsYnD+8XGawBSYiHqjr/iA3PIn4k
            M2NQ8KPFxXDMC7h9vyB7lzMHMIOOyueYFgntTPu7t+jDHs1iZwTquxiyzjF0jU8X
            3RJO7n+Xtkvp/OTatHQwq0EMUimGGNZvsmg46XMlzoZg+HIB9SqzXEfgmZXa5J2u
            SQV3SErnC/keQNYv70SbhhGI3O2Th2OQGvhQrmNHskgkqaeZi4PjKoAG6Lr5pupb
            EMiAcGG39Zf2Oi2uwRZ6hGS7AYkw6uFT3+lt0n38+q+SW/1QtQe3Ds4TKMoUd0w4
            13IPUdLKCAThpoBfY7NdWSW2jexL0T3WG4BWlQIC/rOzMpxA40GTTeZ0wOvMWO8l
            kGjEewB3U5k25xFQOftahIQKOwPuSoP7HyLL4+1Q1OwePQTm2+pRdEFAylADllul
            O5pcHNHVRr5F3bFYlNMmfT2kCoO/hDMpoFr9faMUL7fKKeYb/5BMS2agaUAeg8+w
            IlbhA+Jn6MdyAiJEPVFhJOv6kS8miVB5HNpNVRspNvpEORYwVo0SjE6IqjGL8TXi
            OrXlGre96WZ5lzZ/72b4/EB5G5U2SKpr49F0ag75EwOk19lje6VbraFBc11X4XjU
            ZgEJAhAfuh0YaCxdppYLCFhIghuwG0UhOcJ9mxcEBOKd3K+wLYPVAnLEqLrEVt52
            14IcmZKf50fzwPRcmHaJslNnH2NsTTkeqtmWadOfDqmd+6YATwYZJbxC55T0A6cz
            rZp7WVf9dw==
            =V16c
            -----END PGP MESSAGE-----
          fp: CC3248CD7FFAD043BD8C51B3E5690E38FAF86EEB
        - created_at: "2024-06-29T23:29:20Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DHfhkqE7LHSASAQdAhTiN2Arh1wCKDuGPkjhWDqNQwJ7UVkxo0YMRgAES/kkw
            3PHZWaxrifFsYFg16UGqnZyxa38RaB8YA5QhQgx2zyVE6bCyXtEvVsJX9R93/5kZ
            1GYBCQIQqre4edLn8mb6WXMAI76v2BLb5pd7NV8+tmN42dez2YK+f0RQ5rctfVe7
            1sXvPUeLTWZME7QG9pwrHIH2SVEd0vFjlghAHNjm7Ug2JNIGJWY0LOgx/AGQMEYX
            0/yDCuMOJG8=
            =YIz1
            -----END PGP MESSAGE-----
          fp: E39A9ADC5719F27F46267014C7339B5CD6A9FAB1
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
