apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  interval: 5m
  chart:
    spec:
      chart: rook-ceph
      version: v1.14.5
      sourceRef:
        kind: HelmRepository
        name: rook-release
        namespace: flux-system
      interval: 1m
  values:
    csi:
      serviceMonitor:
        enabled: true
    monitoring:
      enabled: true
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rook-ceph-cluster
  namespace: rook-ceph
spec:
  interval: 5m
  chart:
    spec:
      chart: rook-ceph-cluster
      version: v1.14.6
      sourceRef:
        kind: HelmRepository
        name: rook-release
        namespace: flux-system
      interval: 1m
  values:
    cephClusterSpec:
      storage:
        deviceFilter: nvme0n1
    cephObjectStores: []
    monitoring:
      enabled: true
      createPrometheusRules: true
    operatorNamespace: rook-ceph
    toolbox:
      enabled: true
