---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns
spec:
  interval: 30m
  chart:
    spec:
      chart: external-dns
      version: 1.16.0
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: flux-system
  values:
    provider: cloudflare
    domainFilters:
      - ${CLUSTER_DOMAIN}
    sources:
      - crd
      - ingress
    env:
      - name: CF_API_TOKEN
        valueFrom:
          secretKeyRef:
            name: external-dns
            key: CF_API_TOKEN
    serviceMonitor:
      enabled: true
