---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: volsync
  namespace: volsync-system
spec:
  interval: 30m
  chart:
    spec:
      chart: volsync
      version: 0.12.1
      sourceRef:
        kind: HelmRepository
        name: backube
        namespace: flux-system
  values:
    image:
      repository: ghcr.io/home-operations/volsync
    metrics:
      disableAuth: true
    restic:
      repository: ghcr.io/home-operations/volsync
