apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sabnzbd
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 3.2.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 1m
  values:
    defaultPodOptions:
      securityContext:
        runAsUser: 65534
        runAsGroup: 65534
        fsGroup: 65534
        fsGroupChangePolicy: OnRootMismatch

    controllers:
      sabnzbd:
        replicas: 1
        containers:
          sabnzbd:
            image:
              repository: ghcr.io/onedr0p/sabnzbd
              tag: "4.3.2@sha256:eb884c824b3b109891bdae3eb58fff918d8235637b658a8abb03355ba1368379"
              pullPolicy: IfNotPresent
            env:
              SABNZBD__HOST_WHITELIST_ENTRIES: >-
                sabnzbd,
                sabnzbd.default,
                sabnzbd.default.svc,
                sabnzbd.default.svc.cluster,
                sabnzbd.default.svc.cluster.local,
                sabnzbd.taild1477.ts.net
            resources:
              limits:
                memory: 4096Mi
              requests:
                cpu: 100m
                memory: 256Mi
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  periodSeconds: 5
                  failureThreshold: 30
    service:
      sabnzbd:
        controller: sabnzbd
        ports:
          http:
            port: 8080

    ingress:
      sabnzbd:
        className: tailscale
        hosts:
          - host: sabnzbd
            paths:
              - path: /
                service:
                  identifier: sabnzbd
                  port: http
        tls:
          - hosts:
              - sabnzbd

    persistence:
      config:
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 50Mi
        globalMounts:
          - path: /config
      media:
        type: nfs
        server: 192.168.254.47
        path: /mnt/nas
