---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/volsync.backube/replicationdestination_v1alpha1.json
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: "${APP}-bootstrap"
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  trigger:
    manual: restore-once
  restic:
    repository: "${APP}-volsync-r2"
    copyMethod: Snapshot
    cacheStorageClassName: "${VOLSYNC_CACHE_SNAPSHOTCLASS:-longhorn-cache}"
    cacheAccessModes: ["${VOLSYNC_CACHE_ACCESSMODES:-ReadWriteOnce}"]
    storageClassName: "${VOLSYNC_STORAGECLASS:-longhorn-cache}"
    volumeSnapshotClassName: "${VOLSYNC_SNAPSHOTCLASS:-longhorn}"
    accessModes: ["${VOLSYNC_ACCESSMODES:-ReadWriteOnce}"]
    capacity: "${VOLSYNC_CAPACITY:-1Gi}"
    cleanupCachePVC: true
    moverSecurityContext:
      runAsUser: 65534
      runAsGroup: 65534
      fsGroup: 65534
