apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: 1password
  namespace: flux-system
spec:
  interval: 1h
  url: https://raw.githubusercontent.com/1Password/connect-helm-charts/main
