---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: coredns
  namespace: kube-system
spec:
  interval: 30m
  chart:
    spec:
      chart: coredns
      version: 1.37.0
      sourceRef:
        kind: HelmRepository
        name: coredns
        namespace: flux-system
  values:
    fullnameOverride: coredns
    k8sAppLabelOverride: kube-dns
    replicaCount: 2
    service:
      name: kube-dns
      ClusterIP: 10.96.0.10
    serviceAccount:
      create: true
    prometheus:
      service:
        enabled: true
      monitor:
        enabled: true
    servers:
      - zones:
          - zone: .
            scheme: dns://
            use_tcp: true
        port: 53
        plugins:
          - name: errors
          - name: health
            configBlock: |-
              lameduck 5s
          - name: ready
          - name: log
            configBlock: |-
              class error
          - name: prometheus
            parameters: 0.0.0.0:9153
          - name: kubernetes
            parameters: cluster.local in-addr.arpa ip6.arpa
            configBlock: |-
              pods insecure
              fallthrough in-addr.arpa ip6.arpa
          - name: forward
            parameters: . /etc/resolv.conf
          - name: cache
            parameters: 30
          - name: loop
          - name: reload
          - name: loadbalance
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: node-role.kubernetes.io/control-plane
                  operator: Exists
    tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
