---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-tunnel
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: cloudflare-tunnel
    creationPolicy: Owner
    template:
      data:
        TUNNEL_TOKEN: |-
          {{ toJson (dict "a" .account_id "t" .tunnel_id "s" .tunnel_secret) | b64enc }}
        TUNNEL_ID: "{{ .tunnel_id }}"
  data:
    - secretKey: account_id
      remoteRef:
        key: cloudflare
        property: account_id
    - secretKey: tunnel_id
      remoteRef:
        key: cloudflare
        property: tunnel_id
    - secretKey: tunnel_secret
      remoteRef:
        key: cloudflare
        property: tunnel_secret
