apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-secret
stringData:
  TUNNEL_ID: ENC[AES256_GCM,data:O0YarMTNjntU0PDHbZXWaoU0Ahsc1Uo0anJpeH9KBz7D1V68,iv:/d0BBhU5eaPsyCs0Am8ovuLEduxHAwiVKrg/floV4/8=,tag:2gLoFn9wQWCxzBQFVvUvsg==,type:str]
  credentials.json: ENC[AES256_GCM,data:aWjwBSWmm0Mw5IwUJ8Yccdx5Lk/lpNS2aH/kT6GP54CBau2EEQiV/69gCeBLRPa7Ay7bTcxhCmHv7AFk5HUUp41ApI7kaTBOzc4qUfHOxi7BwZvSpyI8+JnNLxDHJEzWhyxrKd9ulp+TBNDzUP33L4GGmDfQcLwZvt5+vrrnDNUiAQvTvnz9oeIxcZms00rRLIMt6FFQBUVfZBDsn6ZJ0/QGmffM6mmc88tUj5TFWA==,iv:i50PTSoy1r7L94M62BcfqAC5dVfHwKDt+PLnnFZSKcE=,tag:OaaswvmUX2j75rSOPmkW8g==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: "2025-01-07T06:42:34Z"
  mac: ENC[AES256_GCM,data:3T61CRZ98JQDarvfFreoaw93xZ2qKbSQhoh+oxQtomhROoAtDYcQ0gozA8pgl29GipedqHPLH8eGfh7Szu5CjnjygazolpZ277gHY5Y3nUFw5rqjw/TjFTeFSdwpHvI5ZzDWxghS+b83QCS6iSNMPMnZWSnXkvdmYn8MzuK5PwQ=,iv:VXZqai0NIlfZwNCCgZaRwvZ5SKuOUqK+lE8SBj/XcqM=,tag:ywTkrawPkLd24yQ+slq8Ug==,type:str]
  pgp:
    - created_at: "2025-01-07T06:42:34Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA5DuDCLnNCw6AQ/9Gr9LlEScJkhQWK8V1A61osjp1fGqHCQrs7cW2Hi8OxY8
        tsKo+4Ptv1bleXxlSt++0chpkzgGhEL1ALKpGEBSs5CWwwaus3bAXSxyC9Y7G1RO
        iO5veZuaVSwCM5D1AFSNAVWjz1sDZqa7WKZFScsJAXndW94qTI+mFkP4L0QQj0nZ
        EgtDz7W5tjJ2wZpQkzx/FImrRi5drSSBV5znv62cEjKKHqw3+8TPDjRNbO181I/z
        EC6tobS0kmPDj8Py4fjrTy0tNTjJjXRilwz0NJCOW42TNLrwLUDm/aZQO10ruhPA
        3XTJzjPmlXelel1JduHFMcxXkO61GQVWuY72Dkfyq02HPm5uO/yyf/EZNWMlU0EO
        tr74rhc0vfah1IjK8T4pP2tin9GtrnsSjYwyrlE3aQoCAc0YzMIaIitBUgZtlPfL
        IKavofoOAOpKJXqSiFjDtWo0VLhOshOP/qEeXnAJ1kRqXrc+1zPcLOL5v+RxdmsN
        CEZ3uGIjFplSgaQEp0gqF+iqAMy1j0yrQyhlfjwcap7FyTsRBxTDJgV3XV554RBC
        75IddtURqDwMOvl7gU4KA2rLbtVnq5xBDxqKS8DxyD4g1gxJebZiFUcOyIvrOCi0
        Ax//RhdK/K466IJ5sDSPYBe6NGvCOEcgak1irjP2wxpjN5w2/z2GnIpu61xop8XU
        ZgEJAhBCEMrzdqfn1d5Kr5VJuUzb81kMpxbQ+pIOL3d3WsxpkHOHfLNP7ab398G2
        pGOtz1AEY53XA47Oi9coPA7PjJ0hbld8Kbyx4QoK3gKFCs+ypnjg5TssKbQ/ZmW/
        jGaeycB3NA==
        =DhYO
        -----END PGP MESSAGE-----
      fp: 050787E6CDC4F90636141B1D2C5BB181A0326054
    - created_at: "2025-01-07T06:42:34Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hF4DHfhkqE7LHSASAQdAfqDY2lJMPB04ddY+JC/V4o67nbrDmP8GndVaDQIU5kEw
        U9DDM0HVgmp9VfePgkoCN5aCXEbAeJhoVI5ph9EJtfX6coO3S74b05psH2McIv2Z
        1GYBCQIQ4codlDa0LJihndOViOw1pgJDSVLXo3pcsqYyvw6DqbhoUFolvEn55BQe
        7+BC4FIT5id39J0IXmRSRQGkQA8bKLrHDgqmc+k06XVfmI1QO7xoUXE5H65tPnWf
        o+Lhdp666ZY=
        =FtTO
        -----END PGP MESSAGE-----
      fp: E39A9ADC5719F27F46267014C7339B5CD6A9FAB1
  encrypted_regex: ^(data|stringData)$
  version: 3.9.2
