---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: grafana
      version: 8.8.5
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      interval: 1m
  values:
    grafana.ini:
      news:
        news_feed_enabled: false
      analytics:
        enabled: false
        reporting_enabled: false
        check_for_updates: false
        check_for_plugin_updates: false
      auth.anonymous:
        enabled: true
        org_name: Main Org.
        org_role: Viewer
      users:
        viewers_can_edit: true
    sidecar:
      dashboards:
        enabled: true
        searchNamespace: ALL
        defaultFolderName: default
        provider:
          foldersFromFilesStructure: true
    datasources:
      datasources.yaml:
        apiVersion: 1
        datasources:
          - name: Prometheus
            type: prometheus
            url: http://prometheus-operated.monitoring.svc.cluster.local:9090
            access: proxy
            isDefault: true
            jsonData:
              manageAlerts: true
              prometheusType: Prometheus
              cacheLevel: "High"
          - name: Alertmanager
            type: alertmanager
            url: http://alertmanager-operated.monitoring.svc.cluster.local:9093
            access: proxy
            jsonData:
              implementation: prometheus
          - name: Loki
            type: loki
            url: http://loki-headless.monitoring.svc.cluster.local:3100
            access: proxy
            jsonData:
              maxLines: 250
    dashboardProviders:
      dashboardproviders.yaml:
        apiVersion: 1
        providers:
          - name: default
            orgId: 1
            folder: ""
            type: file
            disableDeletion: false
            editable: true
            options:
              path: /var/lib/grafana/dashboards/default
    dashboards:
      default:
        prometheus:
          gnetId: 19105
          revision: 5
          datasource: Prometheus
        node-exporter-full:
          gnetId: 1860
          revision: 37
          datasource: Prometheus
        smart:
          gnetId: 22604
          revision: 2
          datasource:
            - { name: DS_PROMETHEUS, value: Prometheus }
        k8s-system-api-server:
          url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-system-api-server.json
          datasource: Prometheus
        k8s-system-coredns:
          url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-system-coredns.json
          datasource: Prometheus
        k8s-views-global:
          url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-views-global.json
          datasource: Prometheus
        k8s-views-namespaces:
          url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-views-namespaces.json
          datasource: Prometheus
        k8s-views-nodes:
          url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-views-nodes.json
          datasource: Prometheus
        k8s-views-pods:
          url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-views-pods.json
          datasource: Prometheus
        cert-manager:
          gnetId: 20842
          revision: 2
          datasource: Prometheus
        flux-control-plane:
          url: https://raw.githubusercontent.com/fluxcd/flux2-monitoring-example/main/monitoring/configs/dashboards/control-plane.json
          datasource: Prometheus
        flux-cluster:
          url: https://raw.githubusercontent.com/fluxcd/flux2-monitoring-example/main/monitoring/configs/dashboards/cluster.json
          datasource: Prometheus
        longhorn:
          gnetId: 16888
          revision: 9
          datasource: Prometheus
        volsync:
          gnetId: 21356
          revision: 3
          datasource:
            - { name: DS_PROMETHEUS, value: Prometheus }
            - { name: VAR_REPLICATIONDESTNAME, value: .*-dst }
        mikrotik:
          gnetId: 13679
          revision: 22
          datasource:
            - { name: DS_PROMETHEUS, value: Prometheus }
    ingress:
      enabled: true
      ingressClassName: internal
      hosts:
        - grafana.${CLUSTER_DOMAIN}
      annotations:
        external-dns.alpha.kubernetes.io/target: internal.${CLUSTER_DOMAIN}
    serviceMonitor:
      enabled: true
