version: '3'

includes:
  ansible: ./ansible/Taskfile.yml

tasks:
  sources:
    dir: k8s/base/flux-system/sources
    cmds:
      - rm kustomization.yaml
      - kustomize create --autodetect
    generates:
      - kustomization.yaml
