apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus-node-exporter
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: prometheus-node-exporter
      version: 1.18.0
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
      interval: 1m
  valuesFrom:
    - kind: ConfigMap
      name: prometheus-node-exporter-values
