---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
  namespace: networking
spec:
  interval: 5m
  chart:
    spec:
      chart: traefik
      version: 20.6.0
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
      interval: 1m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    deployment:
      replicas: 2
    logs:
      access:
        enabled: true
    service:
      type: ClusterIP
      spec:
        clusterIP: 10.43.0.100
      internal:
        type: ClusterIP
    metrics:
      prometheus:
        serviceMonitor:
          interval: 30s
    resources:
      requests:
        cpu: "100m"
        memory: "50Mi"
      limits:
        cpu: "300m"
        memory: "150Mi"
