---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tailscale
  namespace: networking
rules:
- apiGroups:
    - ""
  resources:
    - secrets
  verbs:
    - create
- apiGroups:
    - ""
  resourceNames:
    - tailscale
  resources:
    - secrets
  verbs:
    - get
    - update
    - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tailscale
  namespace: networking
subjects:
- kind: ServiceAccount
  name: tailscale
roleRef:
  kind: Role
  name: tailscale
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tailscale
  namespace: networking
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tailscale-proxy
  namespace: networking
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tailscale
  template:
    metadata:
      labels:
        app: tailscale
    spec:
      serviceAccountName: tailscale
      initContainers:
        # In order to run as a proxy we need to enable IP Forwarding inside
        # the container. The `net.ipv4.ip_forward` sysctl is not allowlisted
        # in Kubelet by default.
      - name: sysctler
        image: busybox
        securityContext:
          privileged: true
        command:
          - /bin/sh
        args:
          - -c
          - sysctl -w net.ipv4.ip_forward=1 net.ipv6.conf.all.forwarding=1
        resources:
          requests:
            cpu: 1m
            memory: 1Mi
      containers:
      - name: tailscale
        imagePullPolicy: IfNotPresent
        image: "ghcr.io/tailscale/tailscale:v1.32"
        env:
        # Store the state in a k8s secret
        - name: TS_KUBE_SECRET
          value: tailscale
        - name: TS_USERSPACE
          value: "false"
        - name: TS_AUTH_KEY
          valueFrom:
            secretKeyRef:
              name: tailscale-auth
              key: TS_AUTH_KEY
              optional: true
        - name: TS_DEST_IP
          value: "10.43.0.100"
        - name: TS_AUTH_ONCE
          value: "true"
        - name: TS_EXTRA_ARGS
          value: "--hostname=homelab"
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
