---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/toolhive.stacklok.dev/mcpserver_v1beta1.json
apiVersion: toolhive.stacklok.dev/v1beta1
kind: MCPServer
metadata:
  name: github
spec:
  groupRef:
    name: homelab
  image: ghcr.io/github/github-mcp-server:v1.14.0@sha256:7aaeeec9ae4fe9a736d100c1ff0798f3c219b5009e05f5d3945fcacb13cc196b
  transport: stdio
  proxyMode: streamable-http
  proxyPort: 8080
  env:
    - name: GITHUB_API_URL
      value: https://api.github.com
    - name: LOG_LEVEL
      value: info
  secrets:
    - name: toolhive-github
      key: GITHUB_PERSONAL_ACCESS_TOKEN
  resources:
    requests:
      cpu: 10m
      memory: 64Mi
    limits:
      memory: 256Mi
