---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: snapshot-controller
spec:
  interval: 30m
  chart:
    spec:
      chart: snapshot-controller
      version: 4.1.1
      sourceRef:
        kind: HelmRepository
        name: piraeus
        namespace: flux-system
  values:
    controller:
      serviceMonitor:
        create: true
      volumeSnapshotClasses:
        - name: longhorn
          annotations:
            snapshot.storage.kubernetes.io/is-default-class: "true"
          driver: driver.longhorn.io
          deletionPolicy: Delete
          parameters:
            type: snap
    webhook:
      enabled: false
