---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
spec:
  interval: 30m
  chart:
    spec:
      chart: longhorn
      version: 1.7.1
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: flux-system
  values:
    defaultSettings:
      createDefaultDiskLabeledNodes: true
    ingress:
      enabled: true
      ingressClassName: nginx
      host: longhorn.${CLUSTER_DOMAIN}
      annotations:
        cert-manager.io/issuer: "letsencrypt"
    metrics:
      serviceMonitor:
        enabled: true
