---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
spec:
  interval: 30m
  chart:
    spec:
      chart: longhorn
      version: 1.9.0
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: flux-system
  values:
    csi:
      attacherReplicaCount: &replicas 1
      provisionerReplicaCount: *replicas
      resizerReplicaCount: *replicas
      snapshotterReplicaCount: *replicas
    persistence:
      defaultClassReplicaCount: 3
      defaultDataLocality: best-effort
    defaultSettings:
      defaultDataLocality: best-effort
      concurrentAutomaticEngineUpgradePerNodeLimit: 1
    ingress:
      enabled: true
      ingressClassName: internal
      host: longhorn.bbck.dev
      annotations:
        external-dns.alpha.kubernetes.io/target: internal.bbck.dev
    metrics:
      serviceMonitor:
        enabled: true
