apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./backube.yaml
  - ./bjw-s.yaml
  - ./cilium.yaml
  - ./csi-driver-nfs.yaml
  - ./grafana.yaml
  - ./ingress-nginx.yaml
  - ./intel.yaml
  - ./jetstack.yaml
  - ./longhorn.yaml
  - ./node-feature-discovery.yaml
  - ./piraeus.yaml
  - ./prometheus-community.yaml
  - ./rook-release.yaml
  - ./tailscale.yaml
