---
apiVersion: infra.contrib.fluxcd.io/v1alpha2
kind: Terraform
metadata:
  name: cloudflare
  namespace: flux-system
spec:
  interval: 1h
  approvePlan: ""
  path: ./terraform/cloudflare
  sourceRef:
    kind: GitRepository
    name: homelab
    namespace: flux-system
  varsFrom:
    - kind: Secret
      name: terraform-secrets
      varsKeys:
        - cloudflare_api_token
        - cloudflare_account_id
  vars:
    - name: domains
      value:
        bbck.dev:
          email: true
          rua: null@bbck.dev
        bbck.net:
          email: true
          rua: 478fff8e@in.mailhardener.com
        cheatycheetahs.com:
          email: true
          rua: null@cheatycheetahs.com
        lookitupongoogle.com:
          email: false
          rua: ''
