---
apiVersion: infra.contrib.fluxcd.io/v1alpha2
kind: Terraform
metadata:
  name: mikrotik-rb5009
  namespace: flux-system
spec:
  interval: 1h
  approvePlan: auto
  path: ./terraform/mikrotik-rb5009
  sourceRef:
    kind: GitRepository
    name: homelab
    namespace: flux-system
  varsFrom:
    - kind: Secret
      name: terraform-secrets
