apiVersion: ENC[AES256_GCM,data:nn4=,iv:CCFxDNrHsxVjnJmFM0h0jMJD016+WvcICWTlVUojBmY=,tag:+L2uFElG+SWvHx7f3ZePJQ==,type:str]
kind: ENC[AES256_GCM,data:if/OyWyE,iv:9v4gbKV7gY9JLg2EAIdBem56mPPcIxCWdahcEdOiOEE=,tag:ZXrpv8xdiEXn1BiX+lBHDQ==,type:str]
metadata:
  name: ENC[AES256_GCM,data:YAl9sdyLZm4TZWZhb4o8RsM=,iv:v0HMhWRPyKykU2gAHsHeYRf54higWeYgB1iJmxsta2g=,tag:mwj+IheOGC2XLJX/0nHwBw==,type:str]
stringData:
  routeros_password: ENC[AES256_GCM,data:b1t9/jk+P1jDFVW3jVx4kHsvGjM=,iv:zOHC6Ht3OwIoU+t1BgtYA6Nmfa0Bd8b/PCaplqzm0Zc=,tag:al5zxhf4rEiN9H4MMyz9Cg==,type:str]
  cloudflare_api_token: ENC[AES256_GCM,data:UbbzgsrArGvSwGfMuv48DLmHmFBf2s8MUzhVdxTatQPVVgwx812i6A==,iv:8AXPUKdWwC5VS2I31V8uQcJW15WHxQXjJUA3nDTC1rA=,tag:/+0HSVQfQR8CRMFSOksYZg==,type:str]
  cloudflare_account_id: ENC[AES256_GCM,data:9vP0++HlEeAl3fM4NIcfUHq9NHw+25zvjrtkFCXvgc0=,iv:bcWy+FJ03qwUTmQPMpsfjcNvKcc64L4F+pcgIAcDsn8=,tag:lPcUMo+UnhEMdCQVcNQdFA==,type:str]
  domains: ENC[AES256_GCM,data:K6CzNx5Fi3BwI7VEghOLj5oPksLdK0PVYczUcxnpA/hYTslZ3I0wSeA0aFE1td6WAyp4Py8uO99yhfuQd3kCdbwXjsU5Abl5c0x+3DXp0Osl7sG9JTaiIfsd3KWHHpqUVNkhs7zTtk3Zovx42jBrlUWUCnshy6KE4097RCbgeYBawdibwFdPMOlc2yz6mndSaJDQk4a8wIbF4HmqWA4xkqzPIR942YNnpsyVsy8SYAGj0ZApExJJEGO4Tkv/J+a2UnD0e19qoo2tEGpV4rXRkCjtRj9Cky2tbfgfGQvBM5nNAocdRoouEjt+MjifYqjwc3E8xaFLUCqzmEmmSvFv4Q1ESRZM5fwFYELP/iFqtpHJSGkvxU+Wb885jMqtnxLdJh23mpAHvOm+q2pGOTAa8gz6TrVrPPzBTRbi025z1tbj+f+Xw7+zaZ1CYpKujBwCRAh/u++aKT6LdLycYtm8AdbMfwnmCDGzh70JDQ4hAygSzkmeIJVCwWSAJyWhE/jVcXmZ2ggP4rfhpvYLI8BFhkQZX+WBsgmC1VN0RwyP3kChp8h9uvRtJ+oXhMX3Sd0qkY/KtpFIhqBeI0ccIuk2X1aiWN3H7ed2O//Y/TUqFO6Gq0Oz3ioec7AAK8JHC0p3sWyO8TgYs3ONRakg4TozAu/wdb0wTi2AnrCgiw==,iv:/cefmMy30u2/Zgc6OHUuDrUWRuDjmZDvsQYFM2s8/Q4=,tag:bhmRv2gLKNKmEKTu3DxIAA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: "2025-03-30T04:34:56Z"
  mac: ENC[AES256_GCM,data:dgZEinqFZxmHbp6c9NpqGT1+TVJQiAIlKYoQjE2SJVb5SaKeMiLJfdeNlMnp6TgJX5KyQkJROhk9XuoeDS5tieIMsh02GIlpV9tYHUVHIzXBMxb6OPfxEoXW4SepMHNI9VY6flzzYJ6wjHpjC4t/SAUYpaS5Mykuvg7jFmtosJ4=,iv:Y41pLk++/on/DvqsoLW/XoZ8qYwQWfOL/60bS9lMVbA=,tag:sR1LWHnWCcGAkQ2OjP6vug==,type:str]
  pgp:
    - created_at: "2025-03-30T04:34:56Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hF4DHfhkqE7LHSASAQdAWk7sjVGAx+Fmg8yhagm3AGLbdnJfa5Pme5hG7+WHc0ww
        qrXSoc96DWJHUOhJ/eEgH+0sHYDrvQWJVh79lYBzPULWYi2BEjZhSDiSgL/eXnKN
        1GgBCQIQz+p1RybT44Sr9r9ub4vrAz0QtzQG9b73O/JgTIQES8j1x0vv4lH3Vkts
        5On+wezYVyIt+1Nd0RSvpwKh/I37RSmhWb1EgtuuXGO6pwHCRYG/EAhDZ/d95P2C
        F2H2K9UiFK0bCw==
        =Zv2q
        -----END PGP MESSAGE-----
      fp: E39A9ADC5719F27F46267014C7339B5CD6A9FAB1
  unencrypted_suffix: _unencrypted
  version: 3.9.4
