---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./2dot5-gbe.yaml
  - ./apc-ups.yaml
  - ./intel-gpu-device.yaml
