---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: openebs
  namespace: openebs-system
spec:
  interval: 5m
  chart:
    spec:
      chart: openebs
      version: 4.1.0
      sourceRef:
        kind: HelmRepository
        name: openebs
        namespace: flux-system
      interval: 1m
  values:
    engines:
      local:
        lvm:
          enabled: false
        zfs:
          enabled: true
      replicated:
        mayastor:
          enabled: false
    localpv-provisioner:
      rbac:
        create: true
    openebs-crds:
      csi:
        volumeSnapshots:
          enabled: false
    zfs-localpv:
      enabled: true
      crds:
        zfsLocalPv:
          enabled: false
        csi:
          volumeSnapshots:
            enabled: true
