apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: volsync
  namespace: volsync-system
spec:
  interval: 5m
  chart:
    spec:
      chart: volsync
      version: 0.9.1
      sourceRef:
        kind: HelmRepository
        name: backube
        namespace: flux-system
      interval: 1m
  values:
    image:
      repository: ghcr.io/onedr0p/volsync
    metrics:
      disableAuth: true
    restic:
      repository: ghcr.io/onedr0p/volsync
