---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "${CLUSTER_DOMAIN/./-}"
spec:
  secretName: "${CLUSTER_DOMAIN/./-}-tls"
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  commonName: "bbck.dev"
  dnsNames:
    - "bbck.dev"
    - "*.bbck.dev"
