---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: flux-instance
spec:
  interval: 5m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.32.0
  url: oci://ghcr.io/controlplaneio-fluxcd/charts/flux-instance
---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: flux-instance
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: flux-instance
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    instance:
      distribution:
        # renovate: datasource=github-releases depName=controlplaneio-fluxcd/distribution
        version: 2.7.2
      cluster:
        networkPolicy: false
      components:
        - source-controller
        - kustomize-controller
        - helm-controller
        - notification-controller
      sync:
        kind: GitRepository
        name: homelab
        url: https://github.com/bbck/homelab
        ref: refs/heads/master
        path: k8s/flux
        interval: 1h
      kustomize:
        patches:
          # Recomended flux scaling improvements
          # https://fluxcd.io/flux/installation/configuration/vertical-scaling/
          - patch: |
              - op: add
                path: /spec/template/spec/containers/0/args/-
                value: --concurrent=10
              - op: add
                path: /spec/template/spec/containers/0/args/-
                value: --requeue-dependency=5s
            target:
              kind: Deployment
              name: "(kustomize-controller|helm-controller|source-controller)"
          - patch: |
              apiVersion: apps/v1
              kind: Deployment
              metadata:
                name: all
              spec:
                template:
                  spec:
                    containers:
                      - name: manager
                        resources:
                          limits:
                            memory: 2Gi
            target:
              kind: Deployment
              name: "(kustomize-controller|helm-controller|source-controller)"
          - patch: |
              - op: add
                path: /spec/template/spec/containers/0/args/-
                value: --concurrent=20
              - op: replace
                path: /spec/template/spec/volumes/0
                value:
                  name: temp
                  emptyDir:
                    medium: Memory
            target:
              kind: Deployment
              name: kustomize-controller
          - patch: |
              - op: add
                path: /spec/template/spec/containers/0/args/-
                value: --helm-cache-max-size=10
              - op: add
                path: /spec/template/spec/containers/0/args/-
                value: --helm-cache-ttl=60m
              - op: add
                path: /spec/template/spec/containers/0/args/-
                value: --helm-cache-purge-interval=5m
            target:
              kind: Deployment
              name: source-controller
          # Disable OCI repo helm chart digest tracking
          # https://github.com/fluxcd/flux2/issues/4910
          - patch: |
              - op: add
                path: /spec/template/spec/containers/0/args/-
                value: --feature-gates=DisableChartDigestTracking=true
            target:
              kind: Deployment
              name: helm-controller
          # Enable the helm-controller OOM watcher
          - patch: |
              - op: add
                path: /spec/template/spec/containers/0/args/-
                value: --feature-gates=OOMWatch=true
            target:
              kind: Deployment
              name: helm-controller
