---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sonarr
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 3.7.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 1m
  values:
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        runAsGroup: 65534
        fsGroup: 65534
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile:
          type: RuntimeDefault
      nodeSelector:
        # Pin to arm64 since we also pin the container sha256
        kubernetes.io/arch: arm64
    controllers:
      sonarr:
        replicas: 1
        containers:
          sonarr:
            image:
              repository: ghcr.io/onedr0p/sonarr
              tag: "4.0.13.2932@sha256:ada951982555c7f7083fb95228d2e4528a1eadd5159b2959841bb8c690bc281f"
              pullPolicy: IfNotPresent
            env:
              TZ: America/Los_Angeles
            resources:
              limits:
                memory: 1024Mi
              requests:
                cpu: 100m
                memory: 256Mi
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  periodSeconds: 5
                  failureThreshold: 30
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop: ["ALL"]
    service:
      sonarr:
        controller: sonarr
        ports:
          http:
            port: 8989
    ingress:
      sonarr:
        className: internal
        hosts:
          - host: sonarr.${CLUSTER_DOMAIN}
            paths:
              - path: /
                service:
                  identifier: sonarr
                  port: http
        annotations:
          external-dns.alpha.kubernetes.io/target: internal.${CLUSTER_DOMAIN}
    persistence:
      config:
        existingClaim: sonarr
      data:
        type: nfs
        server: 192.168.254.47
        path: /mnt/nas
