apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sonarr
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 3.4.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 1m
  values:
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        runAsGroup: 65534
        fsGroup: 65534
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile:
          type: RuntimeDefault
    controllers:
      sonarr:
        replicas: 1
        containers:
          sonarr:
            image:
              repository: ghcr.io/onedr0p/sonarr
              tag: "4.0.9.2244@sha256:951a35cd1ca2247e5477138b6998f907fa80a8715f3b78d2b4607c7441dcd828"
              pullPolicy: IfNotPresent
            env:
              TZ: America/Los_Angeles
            resources:
              limits:
                memory: 1024Mi
              requests:
                cpu: 100m
                memory: 256Mi
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  periodSeconds: 5
                  failureThreshold: 30
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop: ["ALL"]
    service:
      sonarr:
        controller: sonarr
        ports:
          http:
            port: 8989
    persistence:
      config:
        existingClaim: sonarr
      data:
        type: nfs
        server: 192.168.254.47
        path: /mnt/nas
