---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: generic-device-plugin
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 3.6.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 1m
  values:
    defaultPodOptions:
      priorityClassName: system-node-critical
    controllers:
      generic-device-plugin:
        type: daemonset
        containers:
          app:
            image:
              repository: ghcr.io/squat/generic-device-plugin
              tag: 36bfc606bba2064de6ede0ff2764cbb52edff70d
            args:
              - --log-level=info
              - --config=/config/config.yaml
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 64Mi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop: ["ALL"]
    service:
      app:
        controller: generic-device-plugin
        ports:
          metrics:
            port: 8080
            protocol: HTTP
    serviceMonitor:
      app:
        serviceName: generic-device-plugin
        endpoints:
          - port: metrics
    persistence:
      config:
        type: configMap
        name: generic-device-plugin-config
        globalMounts:
          - path: /config/config.yaml
            subPath: config.yaml
            readOnly: true
      dev:
        type: hostPath
        hostPath: /dev
        globalMounts:
          - readOnly: true
      kubelet:
        type: hostPath
        hostPath: /var/lib/kubelet/device-plugins
    configMaps:
      config:
        data:
          config.yaml: |-
            ---
            devices:
              - name: tun
                groups:
                  - count: 1024
                    paths:
                      - path: /dev/net/tun
