---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: 41.9.1
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
      interval: 1m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    grafana:
      grafana.ini:
        auth.anonymous:
          enabled: true
        server:
          domain: homelab.bbck.net
          root_url: "%(protocol)s://%(domain)s/grafana"
          serve_from_sub_path: true
      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: traefik
        hosts:
          - homelab.bbck.net
        path: /grafana
