apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: csi-driver-nfs
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      chart: csi-driver-nfs
      version: v4.7.0
      sourceRef:
        kind: HelmRepository
        name: csi-driver-nfs
        namespace: flux-system
      interval: 1m
  values:
    controller:
      replicas: 2
      runOnControlPlane: true
