---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
  namespace: kube-system
spec:
  interval: 30m
  chart:
    spec:
      chart: cilium
      version: 1.16.4
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: flux-system
  values:
    ipam:
      mode: kubernetes
    k8sServiceHost: localhost
    k8sServicePort: 6443
    kubeProxyReplacement: true
    operator:
      replicas: 1
    socketLB:
      hostNamespaceOnly: true
