---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-nginx-internal
spec:
  interval: 30m
  chart:
    spec:
      chart: ingress-nginx
      version: 4.12.0
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
  values:
    fullnameOverride: ingress-nginx-internal
    controller:
      config:
        ssl-redirect: "true"
        force-ssl-redirect: "true"
      admissionWebhooks:
        objectSelector:
          matchExpressions:
            - key: ingress-class
              operator: In
              values: ["internal"]
      replicaCount: 2
      extraArgs:
        default-ssl-certificate: networking/${CLUSTER_DOMAIN/./-}-tls
      service:
        type: LoadBalancer
        loadBalancerClass: tailscale
        annotations:
          external-dns.alpha.kubernetes.io/hostname: internal.${CLUSTER_DOMAIN}
          tailscale.com/hostname: k8s-nginx
      ingressClassResource:
        name: internal
        default: true
        controllerValue: k8s.io/internal
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
