apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - release.yaml
configMapGenerator:
  - name: prometheus-values
    files:
      - values.yaml
configurations:
  - kustomizeconfig.yaml
