apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: traefik
resources:
  - namespace.yaml
  - release.yaml
configMapGenerator:
  - name: traefik-values
    files:
      - values.yaml
secretGenerator:
  - name: traefik
    files:
      - CF_DNS_API_TOKEN=token.encrypted
configurations:
  - kustomizeconfig.yaml
