apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: traefik
resources:
  - namespace.yaml
  - secret.yaml
  - release.yaml
configMapGenerator:
  - name: traefik-values
    files:
      - values.yaml
configurations:
  - kustomizeconfig.yaml
