apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: traefik
      version: 9.18.2
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
      interval: 1m
  valuesFrom:
    - kind: ConfigMap
      name: traefik-values
