---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/gateway.envoyproxy.io/securitypolicy_v1alpha1.json
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: obsidian-mcp
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: obsidian
  apiKeyAuth:
    credentialRefs:
      - group: ""
        kind: Secret
        name: obsidian-mcp-api-keys
    extractFrom:
      - headers:
          - authorization
    sanitize: true
