---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tofu-controller
spec:
  interval: 30m
  chart:
    spec:
      chart: tofu-controller
      version: 0.16.0-rc.5
      sourceRef:
        kind: HelmRepository
        name: tofu-controller
        namespace: flux-system
      interval: 30m
  values:
    runner:
      image:
        repository: ghcr.io/home-operations/opentofu-runner
        tag: 1.10.1@sha256:c947183050322022b1125783c0d8224b5535c37fab6cd89ba8ab88d8ad9e2ed6
    awsPackage:
      install: false
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
        interval: 1m
