---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tofu-controller
spec:
  interval: 30m
  chart:
    spec:
      chart: tofu-controller
      version: 0.16.0-rc.5
      sourceRef:
        kind: HelmRepository
        name: tofu-controller
        namespace: flux-system
      interval: 30m
  values:
    awsPackage:
      install: false
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
        interval: 1m
