---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tofu-controller
spec:
  interval: 30m
  chart:
    spec:
      chart: tofu-controller
      version: 0.16.0-rc.5
      sourceRef:
        kind: HelmRepository
        name: tofu-controller
        namespace: flux-system
      interval: 30m
  values:
    runner:
      image:
        repository: ghcr.io/home-operations/opentofu-runner
        tag: 1.10.2@sha256:fb3d44e5aea7f30d93fc5c5cdde2356d19c888a37bfd1039c5b66f0fadd10aa0
    awsPackage:
      install: false
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
        interval: 1m
