apiVersion: v1
kind: Secret
metadata:
  name: branch-planner-token
stringData:
  token: ENC[AES256_GCM,data:EqwqWCVV/Jaf38+JZYlfFP53UbP+mMoLGYcrqc0/ga56eXz7+aORuw==,iv:IRThvfxvrtSm2YWaQI/j72xdO+VZvaKUxk8cgqTnCv0=,tag:iYOHvfap8whRb+TBcfIWAA==,type:str]
sops:
  lastmodified: "2025-06-13T04:50:42Z"
  mac: ENC[AES256_GCM,data:kjq7NdsxQfPqv4i+C5N3fPbAWFRDIdw1+zK+CS3s7XHtpvE+Luanvagy3InUKOouNhjuVqUZMG2O7Z0J4SQR7PZFl6SiqoW2gw2twD+nCBMRvmvwXoEWaOjeHcffFuJFF9D+/8mDODKmeT2BeNHxhJ/B4f1oy1IYP6W/tWZzgcI=,iv:bOudoj5rHVVnIVVrV74fWYu8ffMjM4jxfq66vqqrgeo=,tag:y0grB+SLuX8nRsztDlOxHQ==,type:str]
  pgp:
    - created_at: "2025-06-13T04:50:42Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA5DuDCLnNCw6ARAAmnXGNiJWo+9WWv1Jsn479EfsnlEOLuwJO/FqN01k0m4Z
        DAtGpTl9o/DgONevUnDmz00ifj82ThVQz4NuaqRpncBpWH++Ll2qqP1IfQNmBcO2
        HapSaKK83hEuwI8xHXstrdB9SxwEBNUBDtXJi+nB/uY7X2ZGIq+VMYtJwU/TjPat
        rprQWf78PjxkFwMp3n4JEPmbMVHsL3zeBRhIEEG7eHy8+Kn7rGCsGIDqooXHNmBF
        UBEj0He0COUl+ABYSWcImJx8ZlqXB8nYlu705P6Sd09y4jjOeDCCSoRAFWpJ4eDE
        NS8XeVKKtRBzWk0+X9z8Dd36SQBAk52IGoHd0/7bUrupY+jmPa46KVc8OOmsVqzp
        SnNvEHSh/XscfDmi2fm63VZWdbiXWNZZ8et77PLN6xEFn/4sLh7olXuSNFGLRlfh
        /2LkpieS8DbyRpFt7bH0gb5Ez4F/R3dM5QIJhG7/wllJL1c33S3Oera97k6gmNRx
        wvlEqCP4+HETLG2Jy2sFdUyPBf4RCGN2LTQbFdhUhcwBdwvQgvZ621bXc4w2Xu1X
        MFWkbdEK76vh/6eki6OkMkRrKXhs2jPVHxUxrupwfL2zElTx72v7qWl7ES2QD5kH
        VUp6HPPPMPgOtHM+HBI3Lp6DmwJbdwk0z76tOlukcdhutFapWqsbfHoCcyz8M/7U
        aAEJAhAS+LbpaScG/BM+5UjRW1px17YdJab9PDkcVjr11YjY7jHMqZ/g9nXn6d1u
        qT9JbaxFpnYu06v6Lrfv3TUsbri6Apq6ABOWNURUlOtK7tcFVN6EObR5HKRgnHDK
        DVKqyMfsnT+j
        =Oq1H
        -----END PGP MESSAGE-----
      fp: 050787E6CDC4F90636141B1D2C5BB181A0326054
    - created_at: "2025-06-13T04:50:42Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hF4DHfhkqE7LHSASAQdAf9qyDR4XmukDO7rK3ZBtSaWgONAN6+/8xy+Bf3A1/xcw
        d0XN7Zi0QLOx30OFnfG2T4L1zHuPXF3v78Hrwy7BpWG1yLiHcwww2APgOKCj+7LI
        1GgBCQIQXEoJG+Ve1DUQGB4ZRS1ryNPyMSSpZxmaqZAeT3AX770WrIMEtBaBk9q8
        P9EPYKKrBmdLw2m0ddE9j1azL0tWpaMuTtDPyV6woyZErnZAeCPBxywqIEwzF5Wd
        /osU2zto7iA4zw==
        =jpYl
        -----END PGP MESSAGE-----
      fp: E39A9ADC5719F27F46267014C7339B5CD6A9FAB1
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
