apiVersion: v1
kind: Secret
metadata:
  name: branch-planner-token
stringData:
  token: ENC[AES256_GCM,data:aiPs1h6licQDjB6+VzvKrpVdeD25sqmFVM3kf+1F/5+nFrnR4Tdo3cai8HULW2w/ai62VS6EZw2fbk4KZypRYKxjMFJ266RiWZqQoG29OXt2wGU+pSN11T0lmD1o,iv:yLNwHJLtw/DHgi2MifDT9CQFOdJkMoO+YrM11fyIE6A=,tag:o4wKVDbOsQpE90Wb/8CpZQ==,type:str]
sops:
  lastmodified: "2025-04-06T05:01:09Z"
  mac: ENC[AES256_GCM,data:OYfUCJEGFKTA+7F1dSvsqj/3Ppmsq+u7kLW1Dmi1PqyNVYOZYuc3tgqAgVwC+9zXmih5JhU/wlWocfEP0zqgyLa+K/RXQCXkzcQ11teq6dwX/InWWp/hucYWjxvgMZ6/O94BPXpDJb+AKuiMR0P76yu0mBRRR9HVLlMHf/d70Pc=,iv:3rgGCevynIpZYMg9RG9zBWnDaQXnk3GOm3mEibYQEHY=,tag:t5kNR2fse/x7GvSkH0tMlg==,type:str]
  pgp:
    - created_at: "2025-04-06T05:01:09Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA5DuDCLnNCw6AQ/9F8u+2GWGQwwaHsxVZScQj3vavl33a5xglkIx/qCCIlnC
        PahJGSL87soBwAYgFboTWe7UBUylnLLJLxssPCgcqEPqC3SpkZfwChejr6x8hHGc
        3x8mn6iNX9rK0Pygg8fMYf1ZstbHBw9zXVsrIV/ACyeuEHlsHPjElW6J0jSreIx3
        uQ1i7FByqbgChj35CImV6MWYuX53ee9Ke/ZeulQsiSVs+34o/XesObU53iTXVTeT
        HAenHNQNZeLh35lzrHa2xIaSXpv/Zu1ewaK32FTsvDZYRtzcVVaQZwEJ0SvDPgE0
        Pkkod3A8rN7vhTXb1z9khtHaIYms7pMRumv9Ri58GfJWsHOHxSQefkDA2p6n7LlK
        8ruBEnXoDmpa8qQNTsJg1QUxg6k0OYajL8rlpPlFWnPwSc0OILvd31o7qfMwBa+r
        rGo/rdMI9DCvZjERXshdXVQJgBAbPm2xNVsC829e458PtIogjKXk9b5L5EnZyIfD
        z4RZhbCQk9IFzcWBihYE0+VtDifozi6CNdiRsGqypfDjxkj/eL6Gvn/Nchk5jnAS
        Dnv5ggaRJmXdYN9uKZkYxHk9ynukWNbZa1pVq6SLHYWG7354O3uXifpfB6dnGoMn
        A27UYm3xeDgw6KCwtzcalo28NlSGVH18TR5ty9I/8p3hn+RcZD5vnL9gNgoTcDnU
        aAEJAhDUSMrqIiilL6dfd9t29geLwFpCFv7xGfqj9OUn9ZfN01RcBVs61BFd97b5
        mWQCpX1LAw+3D49gSNw7M63EwMuCfeQwPbULWCTxzxR20Jh0GEGq9b0JjHZpyqrt
        EydFtjNDuXCx
        =JeqL
        -----END PGP MESSAGE-----
      fp: 050787E6CDC4F90636141B1D2C5BB181A0326054
    - created_at: "2025-04-06T05:01:09Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hF4DHfhkqE7LHSASAQdAXNMvrvkciFz0ojbhlDJ/E2NYUYvUSUD/CPIm7diPEHUw
        avqysboYT8EJ7u7HYmvJryDOooYFqYM1zsWvEQULrikTJTG6DCTBOqBf1jVODXgm
        1GgBCQIQKw7gvLdX4XyvPG4020kurnn7gcNBuAKa0LkGk2zkO9mfI1WJSbNjOwUl
        u6QvoWcbxjJxt85XLgdIQRWH0WVXvVVSMrISXvxEj4dUE8o0oelaMkLy9q3iqLwx
        dSI5tZq2SSl/Ew==
        =LNjO
        -----END PGP MESSAGE-----
      fp: E39A9ADC5719F27F46267014C7339B5CD6A9FAB1
  encrypted_regex: ^(data|stringData)$
  version: 3.10.1
