apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: radarr
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 3.2.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 1m
  values:
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        runAsGroup: 65534
        fsGroup: 65534
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile:
          type: RuntimeDefault
    controllers:
      radarr:
        replicas: 1
        containers:
          radarr:
            image:
              repository: ghcr.io/onedr0p/radarr
              tag: "5.7.0.8882@sha256:00a8d7ced538fc7cba69deb138b1842f2426580e46c5d46644ad2a87fcb92ba7"
              pullPolicy: IfNotPresent
            env:
              TZ: America/Los_Angeles
            resources:
              limits:
                memory: 1024Mi
              requests:
                cpu: 100m
                memory: 256Mi
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  periodSeconds: 5
                  failureThreshold: 30
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop: ["ALL"]
    service:
      radarr:
        controller: radarr
        ports:
          http:
            port: 7878

    ingress:
      radarr:
        className: tailscale
        hosts:
          - host: radarr
            paths:
              - path: /
                service:
                  identifier: radarr
                  port: http
        tls:
          - hosts:
              - radarr

    persistence:
      config:
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 250Mi
        globalMounts:
          - path: /config
      media:
        type: nfs
        server: 192.168.254.47
        path: /mnt/nas
