apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: radarr
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 3.4.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 1m
  values:
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        runAsGroup: 65534
        fsGroup: 65534
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile:
          type: RuntimeDefault
    controllers:
      radarr:
        replicas: 1
        containers:
          radarr:
            image:
              repository: ghcr.io/onedr0p/radarr
              tag: "5.9.1.9070@sha256:3dae331f04e8a70786147e6a158fd1c3473fad4ffb78c9cf0f92955973959733"
              pullPolicy: IfNotPresent
            env:
              TZ: America/Los_Angeles
            resources:
              limits:
                memory: 1024Mi
              requests:
                cpu: 100m
                memory: 256Mi
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  periodSeconds: 5
                  failureThreshold: 30
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop: ["ALL"]
    service:
      radarr:
        controller: radarr
        ports:
          http:
            port: 7878
    persistence:
      config:
        existingClaim: radarr
      data:
        type: nfs
        server: 192.168.254.47
        path: /mnt/nas
