---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sabnzbd
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.6.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        runAsGroup: 65534
        fsGroup: 65534
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile:
          type: RuntimeDefault
      nodeSelector:
        feature.node.kubernetes.io/2.5GbE: "true"
    controllers:
      sabnzbd:
        replicas: 1
        containers:
          sabnzbd:
            image:
              repository: ghcr.io/onedr0p/sabnzbd
              tag: "4.4.1@sha256:dcd5c5dfcd12ed364d6204006eb53a45448c79c425424525750553da0b7dd57d"
              pullPolicy: IfNotPresent
            env:
              SABNZBD__HOST_WHITELIST_ENTRIES: >-
                sabnzbd,
                sabnzbd.default,
                sabnzbd.default.svc,
                sabnzbd.default.svc.cluster,
                sabnzbd.default.svc.cluster.local,
                sabnzbd.bbck.dev
            resources:
              limits:
                memory: 4096Mi
              requests:
                cpu: 100m
                memory: 256Mi
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  periodSeconds: 5
                  failureThreshold: 30
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop: ["ALL"]
    service:
      sabnzbd:
        controller: sabnzbd
        ports:
          http:
            port: 8080
    ingress:
      sabnzbd:
        className: internal
        hosts:
          - host: sabnzbd.${CLUSTER_DOMAIN}
            paths:
              - path: /
                service:
                  identifier: sabnzbd
                  port: http
        annotations:
          external-dns.alpha.kubernetes.io/target: internal.${CLUSTER_DOMAIN}
    persistence:
      config:
        existingClaim: sabnzbd
      data:
        type: nfs
        server: 192.168.254.47
        path: /mnt/nas/usenet
        globalMounts:
          - path: /data/usenet
