---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sabnzbd
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.3.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  # TODO: will dependsOn storage
  dependsOn: []
  values:
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        runAsGroup: 65534
        fsGroup: 65534
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile:
          type: RuntimeDefault
    controllers:
      sabnzbd:
        replicas: 1
        containers:
          sabnzbd:
            image:
              repository: ghcr.io/onedr0p/sabnzbd
              tag: "4.3.3@sha256:960f776f5e0ac151de6b30f4e862af4fb42725abfa7ac7f1651186e762a8625e"
              pullPolicy: IfNotPresent
            env:
              SABNZBD__HOST_WHITELIST_ENTRIES: >-
                sabnzbd,
                sabnzbd.default,
                sabnzbd.default.svc,
                sabnzbd.default.svc.cluster,
                sabnzbd.default.svc.cluster.local,
                sabnzbd.taild1477.ts.net
            resources:
              limits:
                memory: 4096Mi
              requests:
                cpu: 100m
                memory: 256Mi
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  periodSeconds: 5
                  failureThreshold: 30
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop: ["ALL"]
    service:
      sabnzbd:
        controller: sabnzbd
        ports:
          http:
            port: 8080
      hack:
        controller: sabnzbd
        type: NodePort
        ports:
          http:
            port: 8080
            nodePort: 30080
    ingress:
      sabnzbd:
        className: tailscale
        hosts:
          - host: sabnzbd
            paths:
              - path: /
                service:
                  identifier: sabnzbd
                  port: http
        tls:
          - hosts:
              - sabnzbd
    persistence:
      config:
        existingClaim: sabnzbd
      data:
        type: hostPath
        hostPath: /mnt/nas/usenet
        globalMounts:
          - path: /data/usenet
