---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: terraform-backend-secret
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: terraform-backend-secret
    creationPolicy: Owner
  data:
    - secretKey: access_key
      remoteRef:
        key: terraform-bucket
        property: username
    - secretKey: secret_key
      remoteRef:
        key: terraform-bucket
        property: password
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: terraform-secret
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: terraform-secret
    creationPolicy: Owner
  data:
    - secretKey: op_connect_token
      remoteRef:
        key: onepassword-connect
        property: terraform_token
