apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prowlarr
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 3.4.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 1m
  values:
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        runAsGroup: 65534
        fsGroup: 65534
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile:
          type: RuntimeDefault
    controllers:
      prowlarr:
        replicas: 1
        containers:
          prowlarr:
            image:
              repository: ghcr.io/onedr0p/prowlarr
              tag: "1.23.1.4708@sha256:2d612eb8c4316921a7d3928537fe7cb73f80522255d93e2b607513bbc9368724"
              pullPolicy: IfNotPresent
            resources:
              limits:
                memory: 500Mi
              requests:
                cpu: 100m
                memory: 128Mi
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  periodSeconds: 5
                  failureThreshold: 30
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop: ["ALL"]
    service:
      prowlarr:
        controller: prowlarr
        ports:
          http:
            port: 9696
    persistence:
      config:
        existingClaim: prowlarr
