---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: plex
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 3.6.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 1m
  values:
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        runAsGroup: 65534
        fsGroup: 65534
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile:
          type: RuntimeDefault
      nodeSelector:
        feature.node.kubernetes.io/i915-gpu: "true"
    controllers:
      plex:
        containers:
          plex:
            image:
              repository: ghcr.io/onedr0p/plex
              tag: "1.41.3.9314-a0bfb8370@sha256:6843c419cc59caabd78175dbf9534e9a7fbc957789be63287df05fa6c4a20c8d"
              pullPolicy: IfNotPresent
            env:
              TZ: America/Los_Angeles
              PLEX_ADVERTISE_URL: https://plex.${CLUSTER_DOMAIN}
            resources:
              limits:
                gpu.intel.com/i915: 1
                memory: 4096Mi
              requests:
                cpu: 100m
                memory: 2048Mi
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /identity
                    port: 32400
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
              startup:
                enabled: true
                spec:
                  periodSeconds: 5
                  failureThreshold: 30
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop: ["ALL"]
    service:
      plex:
        controller: plex
        type: LoadBalancer
        externalTrafficPolicy: Local
        ports:
          http:
            port: 32400
    ingress:
      plex:
        className: internal
        hosts:
          - host: plex.${CLUSTER_DOMAIN}
            paths:
              - path: /
                service:
                  identifier: plex
                  port: http
        annotations:
          external-dns.alpha.kubernetes.io/target: internal.${CLUSTER_DOMAIN}
    persistence:
      config:
        existingClaim: plex
        globalMounts:
          - path: /config/Library/Application Support/Plex Media Server
      cache:
        existingClaim: plex-cache
        globalMounts:
          - path: /config/Library/Application Support/Plex Media Server/Cache
      logs:
        type: emptyDir
        globalMounts:
          - path: /config/Library/Application Support/Plex Media Server/Logs
      tmp:
        type: emptyDir
      transcode:
        type: emptyDir
      media:
        type: nfs
        server: 192.168.254.47
        path: /mnt/nas/media
        globalMounts:
          - path: /media
            readOnly: true
