apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: longhorn-system
resources:
  - namespace.yaml
  - release.yaml
configMapGenerator:
  - name: longhorn-values
    files:
      - values.yaml
configurations:
  - kustomizeconfig.yaml
