---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: hoarder
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 30m
  values:
    controllers:
      hoarder:
        containers:
          app:
            image:
              repository: ghcr.io/hoarder-app/hoarder
              tag: "0.23.2"
              pullPolicy: IfNotPresent
            env:
              MEILI_ADDR: http://hoarder-meilisearch.default.svc.cluster.local:7700
              BROWSER_WEB_URL: http://hoarder-chrome.default.svc.cluster.local:9222
              DATA_DIR: /data
              NEXTAUTH_URL: https://hoarder.${CLUSTER_DOMAIN}
              DISABLE_SIGNUPS: "true"
            envFrom:
              - secretRef:
                  name: hoarder
            resources:
              limits:
                memory: 1Gi
              requests:
                cpu: 100m
                memory: 128Mi
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
            securityContext:
              capabilities:
                drop: ["ALL"]
      chrome:
        containers:
          app:
            image:
              repository: ghcr.io/zenika/alpine-chrome
              tag: "124"
              pullPolicy: IfNotPresent
            command:
              - chromium-browser
              - --headless
              - --no-sandbox
              - --disable-gpu
              - --disable-dev-shm-usage
              - --remote-debugging-address=0.0.0.0
              - --remote-debugging-port=9222
              - --hide-scrollbars
            resources:
              limits:
                memory: 500Mi
              requests:
                cpu: 100m
                memory: 128Mi
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
            securityContext:
              capabilities:
                drop: ["ALL"]
      meilisearch:
        pod:
          affinity:
            podAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                - labelSelector:
                    matchExpressions:
                      - key: app.kubernetes.io/name
                        operator: In
                        values:
                          - hoarder
                  topologyKey: kubernetes.io/hostname
        containers:
          app:
            image:
              repository: getmeili/meilisearch
              tag: "v1.14.0"
              pullPolicy: IfNotPresent
            env:
              MEILI_NO_ANALYTICS: "true"
            envFrom:
              - secretRef:
                  name: hoarder
            resources:
              limits:
                memory: 256Mi
              requests:
                cpu: 50m
                memory: 64Mi
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
            securityContext:
              runAsNonRoot: true
              runAsUser: 65534
              runAsGroup: 65534
              fsGroup: 65534
              fsGroupChangePolicy: OnRootMismatch
              capabilities:
                drop: ["ALL"]
    service:
      hoarder:
        controller: hoarder
        ports:
          http:
            port: 3000
      chrome:
        controller: chrome
        ports:
          http:
            port: 9222
      meilisearch:
        controller: meilisearch
        ports:
          http:
            port: 7700
    ingress:
      hoarder:
        className: internal
        hosts:
          - host: hoarder.${CLUSTER_DOMAIN}
            paths:
              - path: /
                service:
                  identifier: hoarder
                  port: http
        annotations:
          external-dns.alpha.kubernetes.io/target: internal.${CLUSTER_DOMAIN}
    persistence:
      data:
        existingClaim: hoarder
        advancedMounts:
          hoarder:
            app:
              - path: /data
                subPath: data
          meilisearch:
            app:
              - path: /meili_data
                subPath: meili_data
      cache:
        type: emptyDir
        advancedMounts:
          hoarder:
            app:
              - path: /app/apps/web/.next/cache
    secrets:
      hoarder:
        stringData:
          NEXTAUTH_SECRET: ${HOARDER_NEXTAUTH_SECRET}
          OPENAI_API_KEY: ${HOARDER_OPENAI_API_KEY}
          MEILI_MASTER_KEY: ${HOARDER_MEILI_MASTER_KEY}
