apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "${APP}"
spec:
  accessModes:
    - ReadWriteOnce
  dataSourceRef:
    kind: ReplicationDestination
    apiGroup: volsync.backube
    name: "${APP}-r2"
  resources:
    requests:
      storage: "${VOLSYNC_CAPACITY}"
  storageClassName: "${VOLSYNC_STORAGECLASS:-openebs-hostpath}"
