---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: hajimari
  namespace: hajimari
spec:
  interval: 5m
  chart:
    spec:
      chart: hajimari
      version: 2.0.2
      sourceRef:
        kind: HelmRepository
        name: hajimari
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    hajimari:
      name: Chris
      lightTheme: paper
      darkTheme: espresso
      namespaceSelector:
        any: true
      defaultSearchProvider: DuckDuckGo
      searchProviders:
        - name: DuckDuckGo
          token: d
          icon: simple-icons:duckduckgo
          searchUrl: https://duckduckgo.com/?q={query}
          url: https://duckduckgo.com
    ingress:
      main:
        enabled: true
        ingressClassName: traefik
        hosts:
          - host: homelab
            paths:
              - path: /
                pathType: Prefix
    persistence:
      data:
        enabled: true
        type: emptyDir
    resources:
      requests:
        cpu: 100m
        memory: 128m
