apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps
  namespace: flux-system
spec:
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
  postBuild:
    substituteFrom:
      # - kind: ConfigMap
      #   name: cluster-settings
      - kind: Secret
        name: cluster-secrets
  interval: 10m
  path: ./k8s/cm3588/apps
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
