---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nut-exporter
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 1m
  values:
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        runAsGroup: 65534
        fsGroup: 65534
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile:
          type: RuntimeDefault
    controllers:
      nut-exporter:
        replicas: 1
        containers:
          app:
            image:
              repository: ghcr.io/druggeri/nut_exporter
              tag: 3.1.3
              pullPolicy: IfNotPresent
            env:
              NUT_EXPORTER_SERVER: network-ups-tools.monitoring.svc.cluster.local
              NUT_EXPORTER_SERVERPORT: "3493"
              NUT_EXPORTER_VARIABLES: battery.charge,battery.charge,battery.runtime,battery.voltage,battery.voltage.nominal,input.voltage,input.voltage.nominal,ups.load,ups.status,ups.status
            resources:
              limits:
                memory: 128Mi
              requests:
                cpu: 10m
                memory: 32Mi
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop: ["ALL"]
    service:
      app:
        controller: nut-exporter
        ports:
          metrics:
            port: 9199
            protocol: HTTP
    serviceMonitor:
      app:
        serviceName: nut-exporter
        endpoints:
          - port: metrics
            path: /ups_metrics
