---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nginx
spec:
  interval: 30m
  chart:
    spec:
      chart: ingress-nginx
      version: 4.11.2
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
  values:
    controller:
      config:
        ssl-redirect: "true"
        force-ssl-redirect: "true"
      replicaCount: 1
      extraArgs:
        default-ssl-certificate: networking/${CLUSTER_DOMAIN/./-}-tls
      service:
        type: LoadBalancer
        loadBalancerClass: tailscale
        annotations:
          external-dns.alpha.kubernetes.io/hostname: nginx.${CLUSTER_DOMAIN}
      ingressClassResource:
        default: false
      watchIngressWithoutClass: false
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
