---
- hosts: server
  become: true
  gather_facts: true
  any_errors_fatal: true
  pre_tasks:
    - name: Check if cilium is installed
      ansible.builtin.stat:
        path: /etc/cni/net.d/05-cilium.conf
      register: cilium_check

    - name: Fail if cilium is installed
      ansible.builtin.fail:
        msg: Cilium is already installed
      when: cilium_check.exists is defined

    - name: Pausing for 5 seconds...
      ansible.builtin.pause:
        seconds: 5

  tasks:
    - name: Download cilium-cli archive
      ansible.builtin.get_url:
        dest: /tmp/cilium-linux-arm64.tar.gz
        url: https://github.com/cilium/cilium-cli/releases/latest/download/cilium-linux-arm64.tar.gz
        checksum: sha256:https://github.com/cilium/cilium-cli/releases/latest/download/cilium-linux-arm64.tar.gz.sha256sum
        mode: 0644
      register: cilium_archive
    - name: Extract cilium-cli into /usr/local/bin
      ansible.builtin.unarchive:
        src: "{{ cilium_archive.dest }}"
        remote_src: true
        dest: /usr/local/bin
    - name: Delete cilium binary
      ansible.builtin.file:
        path: "{{ cilium_archive.dest }}"
        state: absent
    - name: Install cilium
      ansible.builtin.command: cilium install --wait
      environment:
        KUBECONFIG: /etc/rancher/k3s/k3s.yaml
    - name: Verify cilium is installed
      ansible.builtin.command: cilium status --wait
      environment:
        KUBECONFIG: /etc/rancher/k3s/k3s.yaml
