---
- name: Install k3s
  hosts: all
  become: true
  gather_facts: true
  any_errors_fatal: true
  pre_tasks:
    - name: Pausing for 5 seconds...
      ansible.builtin.pause:
        seconds: 5

  tasks:
    - name: Install k3s
      ansible.builtin.include_role:
        name: xanmanning.k3s
