---
- name: Uninstall k3s
  hosts: all
  become: true
  gather_facts: true
  any_errors_fatal: true
  pre_tasks:
    - name: Pausing for 5 seconds...
      ansible.builtin.pause:
        seconds: 5
  tasks:
    - name: Uninstall k3s
      ansible.builtin.include_role:
        name: xanmanning.k3s
      vars:
        k3s_state: uninstalled
    - name: Gather list of CNI files to delete
      ansible.builtin.find:
        paths: /etc/cni/net.d
        patterns: "*"
      register: files_to_delete
    - name: Delete CNI files
      ansible.builtin.file:
        path: "{{ item.path }}"
        state: absent
      loop: "{{ files_to_delete.files }}"
    - name: Delete cilium binary
      ansible.builtin.file:
        path: /usr/local/bin/cilium
        state: absent
