---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: smartctl-exporter
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: prometheus-smartctl-exporter
      version: 0.10.0
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
      interval: 1m
  values:
    fullnameOverride: smartctl-exporter
    image:
      repository: ghcr.io/joryirving/smartctl_exporter
      tag: 0.12.0@sha256:6073e6bb6663ec793c3df9c12baeb0fe5c1857ddc677cdc611a9456209980ee3
    config:
      devices:
        - /dev/nvme0n1
    # extraInstances:
    #   - config:
    #       devices:
    #         - /dev/sda
    #     nodeSelector:
    #       type: kubernetes.io/hostname=eq12
    serviceMonitor:
      enabled: true
