---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: smartctl-exporter
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: prometheus-smartctl-exporter
      version: 0.10.0
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
      interval: 1m
  values:
    fullnameOverride: smartctl-exporter
    image:
      repository: ghcr.io/joryirving/smartctl_exporter
      tag: 0.12.0@sha256:e332113da59f930bb19292214e902f8b311753895b402fc420682148fea0f7ed
    config:
      devices:
        - /dev/nvme0n1
    # extraInstances:
    #   - config:
    #       devices:
    #         - /dev/sda
    #     nodeSelector:
    #       type: kubernetes.io/hostname=eq12
    serviceMonitor:
      enabled: true
