---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/dragonflydb.io/dragonfly_v1alpha1.json
apiVersion: dragonflydb.io/v1alpha1
kind: Dragonfly
metadata:
  name: "${APP}-dragonfly"
spec:
  replicas: 1
  args:
    - --proactor_threads=1
  resources:
    requests:
      cpu: 10m
      memory: 192Mi
    limits:
      memory: 384Mi
