---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mcp-grafana
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: mcp-grafana
    creationPolicy: Owner
  data:
    - secretKey: MCP_GRAFANA_SERVER_TOKEN
      remoteRef:
        key: mcp-grafana
        property: SERVER_TOKEN
