---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/grafana.integreatly.org/grafanaserviceaccount_v1beta1.json
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaServiceAccount
metadata:
  name: mcp-grafana
spec:
  name: mcp-grafana
  instanceName: grafana
  role: Viewer
  tokens:
    - name: mcp-grafana
      secretName: mcp-grafana-sa-token
