apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tailscale
  namespace: tailscale
spec:
  interval: 5m
  chart:
    spec:
      chart: tailscale-operator
      version: 1.66.4
      sourceRef:
        kind: HelmRepository
        name: tailscale
        namespace: flux-system
      interval: 1m
  values:
