---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/nfd.k8s-sigs.io/nodefeaturerule_v1alpha1.json
apiVersion: nfd.k8s-sigs.io/v1alpha1
kind: NodeFeatureRule
metadata:
  name: 2dot5-gpe-device
spec:
  rules:
    - name: "2.5gbe"
      labels:
        feature.node.kubernetes.io/2.5GbE: "true"
      matchFeatures:
        - feature: network.device
          matchExpressions:
            operstate: { op: In, value: ["up"] }
            speed: { op: In, value: ["2500"] }
