apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      chart: cilium
      version: 1.15.7
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: flux-system
      interval: 1m
  values:
    ipam:
      mode: kubernetes
    k8sServiceHost: localhost
    k8sServicePort: 6443
    kubeProxyReplacement: true
    operator:
      replicas: 1
    socketLB:
      hostNamespaceOnly: true
