---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: toolhive
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: toolhive
    creationPolicy: Owner
  data:
    - secretKey: TSIDP_CLIENT_SECRET
      remoteRef:
        key: toolhive
        property: TSIDP_CLIENT_SECRET
    - secretKey: SIGNING_KEY
      remoteRef:
        key: toolhive
        property: SIGNING_KEY
    - secretKey: HMAC_KEY
      remoteRef:
        key: toolhive
        property: HMAC_KEY
