---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/toolhive.stacklok.dev/mcpgroup_v1beta1.json
apiVersion: toolhive.stacklok.dev/v1beta1
kind: MCPGroup
metadata:
  name: homelab
spec:
  description: Homelab MCP servers exposed through mcp.bbck.dev
