apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: recyclarr
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 3.2.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 1m
  values:
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        runAsGroup: 65534
        fsGroup: 65534
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile:
          type: RuntimeDefault
    controllers:
      recyclarr:
        type: cronjob
        cronjob:
          schedule: "@daily"
        containers:
          recyclarr:
            image:
              repository: ghcr.io/recyclarr/recyclarr
              tag: "7.1.1"
              pullPolicy: IfNotPresent
            args:
              - "sync"
            env:
              TZ: America/Los_Angeles
            resources:
              limits:
                memory: 128Mi
              requests:
                cpu: 10m
                memory: 32Mi
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop: ["ALL"]
    persistence:
      config:
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 100Mi
        globalMounts:
          - path: /config
      config-file:
        type: configMap
        name: recyclarr-configmap
        globalMounts:
          - path: /config/recyclarr.yml
            subPath: recyclarr.yml
            readOnly: true
      secrets-file:
        type: secret
        name: recyclarr-secrets
        globalMounts:
          - path: /config/secrets.yml
            subPath: secrets.yml
            readOnly: true
