apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: recyclarr
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 3.2.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 1m
  values:
    defaultPodOptions:
      securityContext:
        runAsUser: 65534
        runAsGroup: 65534
        fsGroup: 65534
        fsGroupChangePolicy: OnRootMismatch

    controllers:
      recyclarr:
        type: cronjob
        cronjob:
          # TODO: reduce frequency to daily
          schedule: "@hourly"
        containers:
          recyclarr:
            image:
              repository: ghcr.io/recyclarr/recyclarr
              tag: "6.0.2"
              pullPolicy: IfNotPresent
            args:
              - "sync"
            env:
              TZ: America/Los_Angeles
            envFrom:
              - secretRef:
                  name: recyclarr-secret
            resources:
              limits:
                memory: 128Mi
              requests:
                cpu: 10m
                memory: 32Mi
    persistence:
      config:
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 100Mi
        globalMounts:
          - path: /config
      config-file:
        type: configMap
        name: recyclarr-configmap
        globalMounts:
          - path: /config/recyclarr.yml
            subPath: recyclarr.yml
            readOnly: true
