apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: connect
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: connect
      version: "1.0.1"
      sourceRef:
        kind: HelmRepository
        name: 1password
        namespace: flux-system
      interval: 5m
    values:
