apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: homarr
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 3.1.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: default
      interval: 1m
  values:
    controllers:
      homarr:
        replicas: 1
        containers:
          homarr:
            image:
              repository: ghcr.io/ajnart/homarr
              tag: "0.15.3"
              pullPolicy: IfNotPresent
            env:
              TZ: America/Los_Angeles
              DEFAULT_COLOR_SCHEME: dark
              DISABLE_ANALYTICS: true
            resources:
              limits:
                cpu: 500m
                memory: 512Mi
              requests:
                cpu: 100m
                memory: 256Mi
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  periodSeconds: 5
                  failureThreshold: 30
    service:
      homarr:
        controller: homarr
        ports:
          http:
            port: 7575

    ingress:
      homarr:
        className: tailscale
        hosts:
          - host: homarr
            paths:
              - path: /
                service:
                  identifier: homarr
                  port: http
        tls:
          - hosts:
              - homarr

    persistence:
      config:
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 50Mi
        globalMounts:
          - path: /app/data/configs
      database:
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 50Mi
        globalMounts:
          - path: /app/database
      icons:
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 50Mi
        globalMounts:
          - path: /app/public/icons
