apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - ./plex/helm-release.yaml
  - ./prowlarr/helm-release.yaml
  - ./radarr/helm-release.yaml
  - ./recyclarr/helm-release.yaml
  - ./recyclarr/secret.enc.yaml
  - ./sonarr/helm-release.yaml
  - ./tautulli/helm-release.yaml
configMapGenerator:
  - name: recyclarr-configmap
    namespace: default
    files:
      - recyclarr.yml=./recyclarr/recyclarr.yml
generatorOptions:
  disableNameSuffixHash: true
