apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
  storageClassName: ceph-filesystem
