---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: toolhive-karakeep
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: toolhive-karakeep
    creationPolicy: Owner
  data:
    - secretKey: KARAKEEP_API_KEY
      remoteRef:
        key: karakeep
        property: MCP_API_KEY
