---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tsidp
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: tsidp
    creationPolicy: Owner
    template:
      data:
        TS_AUTHKEY: "{{ .TS_AUTHKEY }}?ephemeral=false"
  data:
    - secretKey: TS_AUTHKEY
      remoteRef:
        key: tsidp
        property: TS_AUTHKEY
