---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: karakeep
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 4.4.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 30m
  values:
    controllers:
      karakeep:
        containers:
          app:
            image:
              repository: ghcr.io/karakeep-app/karakeep
              tag: 0.27.1
            env:
              MEILI_ADDR: http://karakeep-meilisearch.default.svc.cluster.local:7700
              BROWSER_WEB_URL: http://karakeep-chrome.default.svc.cluster.local:9222
              DATA_DIR: /data
              NEXTAUTH_URL: https://karakeep.bbck.dev
              DISABLE_SIGNUPS: "true"
              DISABLE_NEW_RELEASE_CHECK: "true"
            envFrom:
              - secretRef:
                  name: karakeep
            resources:
              limits:
                memory: 1Gi
              requests:
                cpu: 10m
                memory: 32Mi
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
            securityContext:
              capabilities:
                drop: ["ALL"]
      chrome:
        containers:
          app:
            image:
              repository: ghcr.io/zenika/alpine-chrome
              tag: "124"
              pullPolicy: IfNotPresent
            command:
              - chromium-browser
              - --headless
              - --no-sandbox
              - --disable-gpu
              - --disable-dev-shm-usage
              - --remote-debugging-address=0.0.0.0
              - --remote-debugging-port=9222
              - --hide-scrollbars
            resources:
              limits:
                memory: 500Mi
              requests:
                cpu: 10m
                memory: 32Mi
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
            securityContext:
              capabilities:
                drop: ["ALL"]
      meilisearch:
        pod:
          affinity:
            podAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                - labelSelector:
                    matchExpressions:
                      - key: app.kubernetes.io/name
                        operator: In
                        values:
                          - karakeep
                      - key: app.kubernetes.io/controller
                        operator: In
                        values:
                          - karakeep
                  topologyKey: kubernetes.io/hostname
        containers:
          app:
            image:
              repository: getmeili/meilisearch
              tag: v1.22.0
            args:
              - /bin/meilisearch
              - --experimental-dumpless-upgrade
            env:
              MEILI_NO_ANALYTICS: "true"
            envFrom:
              - secretRef:
                  name: karakeep
            resources:
              limits:
                memory: 1Gi
              requests:
                cpu: 10m
                memory: 32Mi
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
            securityContext:
              runAsNonRoot: true
              runAsUser: 65534
              runAsGroup: 65534
              fsGroup: 65534
              fsGroupChangePolicy: OnRootMismatch
              capabilities:
                drop: ["ALL"]
    service:
      app:
        forceRename: karakeep
        controller: karakeep
        ports:
          http:
            port: 3000
      chrome:
        controller: chrome
        ports:
          http:
            port: 9222
      meilisearch:
        controller: meilisearch
        ports:
          http:
            port: 7700
    ingress:
      karakeep:
        className: internal
        hosts:
          - host: karakeep.bbck.dev
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        annotations:
          external-dns.alpha.kubernetes.io/target: internal.bbck.dev
    persistence:
      data:
        existingClaim: karakeep
        advancedMounts:
          karakeep:
            app:
              - path: /data
                subPath: data
          meilisearch:
            app:
              - path: /meili_data
                subPath: meili_data
      cache:
        type: emptyDir
        advancedMounts:
          karakeep:
            app:
              - path: /app/apps/web/.next/cache
