---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/volsync.backube/replicationsource_v1alpha1.json
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: prowlarr-r2
  namespace: default
spec:
  sourcePVC: prowlarr-config
  trigger:
    schedule: "0 * * * *"
  restic:
    repository: prowlarr-volsync-r2
    pruneIntervalDays: 7
    retain:
      hourly: 24
      daily: 7
      weekly: 4
    copyMethod: Snapshot
    cacheStorageClassName: ceph-block
    cacheAccessModes: [ReadWriteOnce]
    storageClassName: ceph-block
    volumeSnapshotClassName: ceph-block
    moverSecurityContext:
      runAsUser: 65534
      runAsGroup: 65534
      fsGroup: 65534
