apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prowlarr
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 3.2.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 1m
  values:
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        runAsGroup: 65534
        fsGroup: 65534
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile:
          type: RuntimeDefault
    controllers:
      prowlarr:
        replicas: 1
        containers:
          prowlarr:
            image:
              repository: ghcr.io/onedr0p/prowlarr
              tag: "1.19.0.4568@sha256:ab2ef20ee46f45c924fbdc254802e2434ec4b54fb592fbe72a690c2bdb7c0f73"
              pullPolicy: IfNotPresent
            resources:
              limits:
                memory: 500Mi
              requests:
                cpu: 100m
                memory: 128Mi
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  periodSeconds: 5
                  failureThreshold: 30
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop: ["ALL"]
    service:
      prowlarr:
        controller: prowlarr
        ports:
          http:
            port: 9696

    ingress:
      prowlarr:
        className: tailscale
        hosts:
          - host: prowlarr
            paths:
              - path: /
                service:
                  identifier: prowlarr
                  port: http
        tls:
          - hosts:
              - prowlarr

    persistence:
      config:
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 250Mi
        globalMounts:
          - path: /config
