---
k3s_control_node: true
k3s_server:
  write-kubeconfig-mode: "0644"
  flannel-backend: "none"
  disable:
    - flannel
    - metrics-server
    - servicelb
    - traefik
  disable-network-policy: true
  disable-cloud-controller: true
  node-taint:
    - "node-role.kubernetes.io/control-plane:PreferNoSchedule"
