---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: onepassword-connect
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        runAsGroup: 65534
        fsGroup: 65534
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile:
          type: RuntimeDefault
    controllers:
      onepassword-connect:
        containers:
          api:
            image:
              repository: docker.io/1password/connect-api
              tag: 1.7.3
            env:
              XDG_DATA_HOME: /config
              OP_HTTP_PORT: &apiPort 8080
              OP_BUS_PORT: 11220
              OP_BUS_PEERS: localhost:11221
              OP_SESSION:
                valueFrom:
                  secretKeyRef:
                    name: onepassword-secret
                    key: 1password-credentials.json
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /heartbeat
                    port: *apiPort
                  initialDelaySeconds: 15
                  periodSeconds: 30
                  failureThreshold: 3
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: *apiPort
                  initialDelaySeconds: 15
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - "ALL"
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 256M
          sync:
            image:
              repository: docker.io/1password/connect-sync
              tag: 1.7.4
            env:
              XDG_DATA_HOME: /config
              OP_HTTP_PORT: &syncPort 8081
              OP_BUS_PORT: 11221
              OP_BUS_PEERS: localhost:11220
              OP_SESSION:
                valueFrom:
                  secretKeyRef:
                    name: onepassword-secret
                    key: 1password-credentials.json
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /heartbeat
                    port: *syncPort
                  initialDelaySeconds: 15
                  periodSeconds: 30
                  failureThreshold: 3
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: *syncPort
                  initialDelaySeconds: 15
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - "ALL"
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 256M
    service:
      app:
        ports:
          http:
            port: *apiPort
    persistence:
      config:
        type: emptyDir
        globalMounts:
          - path: /config
