---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tailscale
  namespace: tailscale
spec:
  interval: 5m
  chart:
    spec:
      chart: tailscale-operator
      version: 1.74.1
      sourceRef:
        kind: HelmRepository
        name: tailscale
        namespace: flux-system
      interval: 1m
  values:
    operatorConfig:
      hostname: cm3588
