---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/postgresql.cnpg.io/cluster_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: "${APP}-db"
spec:
  instances: 1
  storage:
    size: "${CNPG_STORAGE:-1Gi}"
  resources:
    requests:
      cpu: 10m
      memory: 256Mi
    limits:
      memory: 512Mi
  bootstrap:
    initdb:
      database: "${APP}"
      owner: "${APP}"
