---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: "${APP}-db-r2"
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: "${APP}-db-r2"
    template:
      data:
        AWS_ACCESS_KEY_ID: "{{ .AWS_ACCESS_KEY_ID }}"
        AWS_SECRET_ACCESS_KEY: "{{ .AWS_SECRET_ACCESS_KEY }}"
        AWS_ENDPOINT_URL: "https://{{ .R2_ACCOUNT_ID }}.r2.cloudflarestorage.com"
  data:
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: kopiur-r2
        property: AWS_ACCESS_KEY_ID
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: kopiur-r2
        property: AWS_SECRET_ACCESS_KEY
    - secretKey: R2_ACCOUNT_ID
      remoteRef:
        key: cloudflare
        property: account_id
