apiVersion: v1
kind: Service
metadata:
  annotations:
    tailscale.com/tailnet-fqdn: prometheus.taild1477.ts.net
  name: prometheus
  namespace: tailscale
spec:
  externalName: placeholder
  type: ExternalName
