---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: karakeep
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: karakeep
    template:
      data:
        MEILI_MASTER_KEY: "{{ .MEILI_MASTER_KEY }}"
        NEXTAUTH_SECRET: "{{ .NEXTAUTH_SECRET }}"
        OPENAI_API_KEY: "{{ .OPENAI_API_KEY }}"
  dataFrom:
    - extract:
        key: karakeep
