---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 3.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 1m
  values:
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        runAsGroup: 65534
        fsGroup: 65534
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile:
          type: RuntimeDefault
    controllers:
      home-assistant:
        replicas: 1
        containers:
          app:
            image:
              repository: ghcr.io/onedr0p/home-assistant
              tag: 2025.1.0@sha256:2abed005d6bfd8dbe0605bd1d9eb5380b14b657401c5c3880e4ba4fa20e636a1
            resources:
              limits:
                memory: 2Gi
              requests:
                cpu: 100m
                memory: 1Gi
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
            securityContext:
              capabilities:
                drop: ["ALL"]
    service:
      home-assistant:
        controller: home-assistant
        ports:
          http:
            port: 8123
    ingress:
      home-assistant:
        className: nginx
        hosts:
          - host: hass.${CLUSTER_DOMAIN}
            paths:
              - path: /
                service:
                  identifier: home-assistant
                  port: http
        annotations:
          external-dns.alpha.kubernetes.io/target: nginx.${CLUSTER_DOMAIN}
    persistence:
      config:
        existingClaim: home-assistant
