---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 1m
  values:
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        runAsGroup: 65534
        fsGroup: 65534
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile:
          type: RuntimeDefault
    controllers:
      home-assistant:
        replicas: 1
        containers:
          app:
            image:
              repository: ghcr.io/home-operations/home-assistant
              tag: "2025.4.1@sha256:9495fb2aff6e56e13bf8ccc8f57b6e931b37c44ea1ffef69f6ee3fc5a951633a"
            resources:
              limits:
                memory: 2Gi
              requests:
                cpu: 100m
                memory: 1Gi
            probes:
              liveness:
                enabled: true
                port: 8123
              readiness:
                enabled: true
                port: 8123
              startup:
                enabled: true
                port: 8123
            securityContext:
              capabilities:
                drop: ["ALL"]
    service:
      home-assistant:
        controller: home-assistant
        type: LoadBalancer
        externalTrafficPolicy: Local
        ports:
          http:
            port: 8123
          mdns:
            port: 5353
            protocol: UDP
          homekit:
            port: 21063
    ingress:
      home-assistant:
        className: internal
        hosts:
          - host: hass.${CLUSTER_DOMAIN}
            paths:
              - path: /
                service:
                  identifier: home-assistant
                  port: http
        annotations:
          external-dns.alpha.kubernetes.io/target: internal.${CLUSTER_DOMAIN}
    persistence:
      config:
        existingClaim: home-assistant
