apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tailscale
  namespace: networking
rules:
- apiGroups:
    - ""
  resources:
    - secrets
  verbs:
    - create
- apiGroups:
    - ""
  resourceNames:
    - tailscale
  resources:
    - secrets
  verbs:
    - get
    - update
    - patch
