apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./helmrelease.yaml
  - ./secret.enc.yaml
configMapGenerator:
  - name: recyclarr-configmap
    namespace: default
    files:
      - recyclarr.yml=./recyclarr.yml
generatorOptions:
  disableNameSuffixHash: true
