apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./externalsecret.yaml
  - ./helmrelease.yaml
configMapGenerator:
  - name: recyclarr
    namespace: default
    files:
      - config/recyclarr.yml
generatorOptions:
  disableNameSuffixHash: true
