apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-config
    namespace: monitoring
data:
    alertmanager.yaml: ENC[AES256_GCM,data:GtKQgpyZnvXQ5I0bjgrN5lkbd6WBBmascSbnrA8ZRMky8atLk7GehqWczzgfzyBaiGnmSL6N57/UCmCXBVE4nQrP3kLS5kQtUEbIm0VaBLde0/luv2n7xoxfel/WqLeOGnqMVPqth3kevk39Rh058qZkd5J1ZGcFdYOb/LALaSDAFrDMbKLtbMkPbyeGvDzh0TcJD0PQyVZci8JtaG3+xnbxJQLc1JBcduag1sQsQ3jGwa2d4o0w0Tj6sxE0/RK33q1xORDHqcxWkrnXoKVipA4gq4arCUnyTnWiyuDwSsoWBiAXEbJKdxTuXfuXFN+cHnE1t54bN/vZ0iJJy8U3W8WLPgZP2XiECOa8YQ3HcgVi8tajrnn0J3vv2WMNWD/SNvGjWbr59KUSH2C//u8qc/3KsLskNPuANEDKmx33z9vAHu5+MUA6S8yWnoNbyf81gMEi+omiAp4y5bTYLg6Lr59Ivf5Uu9PPeQ0dFcw1ul9DHEguADp1qWM2ZS1jlN4oDToX51a4Inh3UiHRsFJ5ZMv2BsJo/nq4RPlhsmQFSYyY6/+UD8gVUD2tsCti/sG16tF7jj1kOvS50nhr0k+nrisOue9lTXOQVIVkxNcaTffQqkU6Y/eIi7ULYezxcbwISOf2IeA8MZUgFVsvQ62ljWqmXCi0mxyTCqI9Zv1/twEwGMSMoW03p1rfeJ2JFJAOFMdZnBGlD0CGvA64auRl6GQOc1bAY2c5CtS5kqUUj/F93MAuS+Lr+tjwgYu/bjM8oOVf+J43ZchepACJSVxgz70O0U28bTgYcBDvTpaeN5e+HA+LJ/7D9WespUCXu0eZktD+DamadH8nsMrUM+wq6iR8qkZiAb/xsLkCJW2CH5+0LZS5xUnCvxQAvBwA4h2NTxAhy+2V6KuS3HeJQDQ1JWGf/hGI2LCmZAsOV0EysxJL2qQt3pa6DSra2cqDxWPZF2G93iXveXZP2EYpDh8U+Locnf7PFSQYkS11eOOyt6c3s7lbEO1NOTKNTyWWBrKHpecL6Kt5JRQHqnumuJeEyXUI37Nq/b97MLOsBkhSQCL9EIW373yDTuO3a6FtTrEGf8rXZl2xFNVTpYw95BJGY3f2XsR6POUXtvIoImBYNo4cIvFiGYNvru0g1j6PovcwSSO57GCkCm5GbFQ0j9We3fxZWjQipzzgikVlJSv9s9PPMQXue7eIGWJDFwcdSZuTiDp+6ykpztTb/H8PRDRrNSodLk960nT9Jh7d7Cj11hvb8JFFXYETdRfkIq5d+hhekUNoZtEIzt7lZqlIy309W1ywRgcAAzhSmmVw8rGdIU+kHf8iMqLQU7365CsWJRgXoHi6rXTyICQL0swlhQg+MjMPnk5q0zg4NhAEpTvy413PgEAeyci0DWP0wWmgtkjDoUG8YDCuTEZQqz44AQsC5F58r9rgdSVvdoG0TKiV5bQe4DwRYDiaRYt+7XT+Rb1KwetkqyIjkSq4PSNXDOta9//WeMncc/Ety3UqKwqaH2gVgDlbpkOAr1m0FqsIGPkELx3IqAXQjDLlCaRu0qhoT8+gYBg+18Obwe13+CFyJDGwXTFXML+KNu+wvEake3I+3L4pGtgCruOpmJzUa55FhsIWxEpq9+fk2Yu8Rn970tri4clv+nqY1IxQRCgIuzy4uYfLk1PliP1mqBO+9bMSJsMQf4fhoZvwTDwsOr/Qf3/qHHSuvcuquY+kr9hFeEkLVrkuBc34Ch/kRG8wj3kcNB3NhBMWSNZDC6OY8fz4j6xooazV/8ZqmwGgx2yEBKdrx3ijq90Lgy2K5T/vlOIYRgKDZTjh9S3rrmjizJRgGjGac+pPQeapVuM6CyMx9ntwpp/BtBV7pPt3sg/rXahLRoCVmZSNofw1HwfcOb0hufZPUHKHnKSx4PG8uuDRaK5fej9vMw+z4/314fKNEh2gohXFGsB8ZofCNU/7TE488npxvwz1z4prkgAfWePAHilK9Hvvjw==,iv:ym1Ec9C9i4qZ0AByHCo7P21qGI0wWncYDPeLAvyjORE=,tag:1IkduSQrmngFCuQjEvBTpg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-06-10T00:04:25Z"
    mac: ENC[AES256_GCM,data:YMDMyONzXwLzDumxp7wsMNjq+a3XGM5bjK8FMguDqi2JTkdNyp5DnbfizN14VnSD+tKC9hwWw5w4bgUvAYjlxNjGnaIyn256WBEfrM/thOj+65P6Oz097G54YzHvVhyNo2N45Yw3g+jAalyHphsOvptIEbFmg5AVE0XCPZBVw4k=,iv:6bxaEOsvwx57zRMTH5m/bkISFaHgK/ko2WTSm+4wk2c=,tag:nBZs44pA0rNAtLPpM3Ov/Q==,type:str]
    pgp:
        - created_at: "2024-06-10T00:04:25Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA5DuDCLnNCw6AQ//cnxARTENZXQBZFRNgDHpbuy8MQntsPpjBYU/DVQVKSVb
            I1TnVMGUndAondSL/zFERl6Or1OsNi9b2ijbbqRWi5mEdOBRqbdrl68zAT5YWr44
            fET+ZUln49PAldP+mxd1NlX2qqtm7Vof9Vz7YDAVntZEnlvE0oSEcWsIZAvUHW8L
            HSs/rPhDHhh8JR24noVkSMm0LhapMuZDYm+U02k9Xq3Pzz6nnHHY3AR+XFsHOFh3
            2ZUIYqAUJLi90YwcTKqSO1FlNmRZ3PX6mcy08gfMikVXHLvBx6ivaW5C8AViR1c+
            ThCGs1DYuCx25pMra5Pp63PQAgHiB0CUy1I+hkv0pjGu5QdTHguCqHEs3y7ZG7UT
            NNyhdn6nXBEwLmdO8RV6ExgPRsLX2cdiNgjp4eUAqFXpRsM7GHqb87s1WfkV8ahA
            DsmfLoZYlJOeRHZKtft4BhroWRS1+AbywEzs3AOYcqZ3Wzg2ZfZtYo84vCIi79Y1
            Axrt1Rm4cid3ZWdYmk0tejtql2ktg3kIzAF2YkqaTkghD7ihBfNcTgUwtaK+S6Ah
            D+uOAPBKk8iBK45ShZjM+vbXKlJjNMFSetxPKZya+mEyejoN0Uh808KXLxEJjLuj
            jOkjMDpPaMwzFefio6xX9oNd31+wMyhO3hMM+dXttzczH4y2jA9wmDeDf9htM9nU
            aAEJAhBIgdNeNOUKsCXP6FcclDP1hDabvhdJWSzYI34a6SGofLPqKlAP7UbPU9be
            E1PFbsR7MTbkGmxnqSKx3ZJjJQbnGO4+2JcZdJe+YzH20yB69m7x3PDFqUnR1tAm
            PDOTDdp2JT4n
            =shjC
            -----END PGP MESSAGE-----
          fp: 050787E6CDC4F90636141B1D2C5BB181A0326054
        - created_at: "2024-06-10T00:04:25Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DHfhkqE7LHSASAQdAEhBqB+VBKpNm6pCxFElSFgcD+IUbLA4In2UlJXNENRIw
            U5C/hd28NTRwgZXQ5V7gsDYrmH+pi5shVxmETQABk46zWL9oCiWxL951zugYePZ/
            1GgBCQIQzO/y6rDOY1E99JGhDYfUNO+WNb9nBVp3GYMDSYxrSdnXKZISyu3qr86s
            j2ZkGW+nmLX5svkxUFvj56m/c+mPbDdpE1sLXj6uGwbZDU9z1mxCQn3xUOvYFavX
            b6OOCDcs/hiaPA==
            =waqV
            -----END PGP MESSAGE-----
          fp: E39A9ADC5719F27F46267014C7339B5CD6A9FAB1
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
