apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-config
  namespace: monitoring
stringData:
  alertmanager.yaml: ENC[AES256_GCM,data:9avten4hOffAHaMxkSuaC7j5oTlec2jGnmj6rpQiQXuQ7J4Nf+n5lZhD3O1BG2IK6pSM/5wiJTXa8J6tR7elQtfP0Klc5/fzEtCV4oCXQTigYrmyFH1tx/wGuec4bqceaYTafvKOwEpVMUShvLokO81DnAou+Efdcce5VHyx+RWjtJTQmVsK90q3Gqv5WCTiHLUfPCClDliKMB5KCFgIAyY6UQpcGqood5UOrRj/bhRZAGrsilxqybHEw2yIw9CF2GmUqmSznWBJ230LiZUA0UiXQNIobHydP9yQWzBb0mv2GAvNCMCTjJ6mdGWA6RH5BoR4xhXK+1Lhjbux6cCJE0hxxnGCpQF/57FGy0ajYkpkeNs1ifkKw3LL/42P5f4gSpIKCPcWfh+0QTzDlRai0gml6THLIdadFusTkV4Asdz8hus3WGMcsQWY+1t3Uy9zC7SOMrXRSTO+S018GWHXZk6lZDxL5KjMeFrtq5HQnPAhqKBj+diBau4mNiYAF0/jDBviNBkxq+b91b96HfdX6VcfJOSOgkLgfZFX136X/DdHsOmX4OWCv412cih2z4wSTOmPOoVxfNVXiCE/4XWqu1oBCJe4eD/hSh2klquhfosrrJ6VHEfpkAd0xn/q83+jWR0pkfQzFxBgPfJhpHDkEfFtxdiAcEP68FPVsEu9zOhphjzvlwDTgL+gb8/6ZkqypjE5EjAqWdKXgdFk68Lvww+bnB+c4IM91flaKizFq0cOW9LaBkprWRVu2CTP0mZ5cJEBMa1CQVf5QZiaty59PndSBi2P5rbG66UlUj+CKxrSchx3E0xTAgNhz4f11sILClrZUuuyzAN4rx3J21gU2XKOCKCEdz1AW9Z2oVEN31mZ7BSJ64VdAX8YZ1RXTZtT7lJ8l745pgK3jZtQmXflWfgBBCXsvKd7t2Udt3lQdIj+g3a7QyV+XWjaWhMMoQAvVMOPAObrxaGvmfNP+1Uq9UnNgf1DYNNHJuIVgSLeDiHnEZvr6EljEJB9zzyjnbkzUE2ZxYNnTk9Fnremnb1fXz5iQc+juYbPGc6gNlJRZrz5NdCLnmsEGzNGhOp1DPdKRV01x9gHNtH1XNOT/N/98Zibbz9iu639GdG4fESmck2vc3je+ZHtAbr1R3/3gUDHMQqvPIhBIIBCK4gWwaZQMomueBLR4kD2oEN+cv+Qh8VPzgiTDaV9sj9FLEDegamYHIROdhvaIvvtVWchQoHBOb6AlICXAlvNrQBxJAwGEma1dc+Q5KTFuSFXtdLefgkM9CxxDa4BBQWH/E8fJZFt0yHuxtkbOdh9s7ED9lKyt/FKlYIzxne6PypeofccsOap5LqITKKeMuMSMK5ULdu8dPObaZXzOUYMOpbiuvcE6yD+8135UmZ4gWZxl8Nao2UfDf8O492NiD//oj49dPYDnqAWkA1KgwQDRtfBk1bQ5I6FwemBIA/mmXNDHx32le06oNQ1h2cGPASUhJPqaa1sK70ux8iQxTAWKCR/ZELEx2wd3SML1qasi7y9sLYpgOPJWsNhMW5DPtpC89BF2Y3Cipe1jxXZyhjFRqzMOto0aguhpUVsZZ7XpfL2uq/1Bz/ukVQNIeABZCXqVUq+LFwO3+X5B8DsgqGuSxTVbpDxgf7ibtfeCuZqbbCIykk8OMGUGQ==,iv:EgcB2qKZjozJDl7eUa0j69GkluqHab7kd+qX9vkgjpU=,tag:/v21TYqMYab0alBhgUW8xA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: "2024-07-06T03:46:16Z"
  mac: ENC[AES256_GCM,data:mAiRLKNwSNVD74BZb2Ba4vRne7nP5mFUbJ83IbwAP5Un9cBYKiQzJWSSuluXJOJDFI6YZ0I/wed0rmpHxgtE4AkKHqyf8fZ/zVyzdGD5E1ed9VGgoSGkwemrDHTNmoFk0ulwu/HljzLHbNG9k8oATkrPqv2u0qi9/WC+9DgA15k=,iv:Pk+dFAS1iIhr9MYlkh18V+IyBar56+P+iJJo0GI0PsY=,tag:6jpCJ6OhRyWws82bda+sUA==,type:str]
  pgp:
    - created_at: "2024-07-06T03:46:16Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA5DuDCLnNCw6ARAAxqn5Q3reL3tIAt/i39TC2XBWei3DSF0RwzszlOQmaJ2H
        sEXVNALY6DWBRgOcP+7I0D69XBIdNkgSkoZGlsxPAXH6JTSRDor8ElEFQj1/RXGP
        ClbeQIpVvzLb1i4CyXIgrJ8xk4Z0OjYfLipbi0ZgGh3ZO7Gzdy2Ka+VjvIJeluvX
        LkHFv4ndG4O9Kwo8xae/NeMRXTc3GA81p3DsqyiORowI+mFlrcp1yQXfhMekgvpq
        hit23c4kAJuC936K+IUoDQGt1OHp5oGivwqSmIzeEHxNOxZ2legUC+piKFS2addD
        wenomEuZgowPJKsL9kf2PTAhKMq+iLWnRx9lAQa4fuqjtrw1oBfkgBpuloqZ6K5z
        QitZKKJkp5OD9Oi6hk/iCduh2kp26FiW6Cb/PG28dFMWOq9iucdv5FOlsxhUdNPp
        JnVqZUlEXPmTNBhygQM+fHh8SnFkrNaKIBCAkNKUUOjFyXHOp2yIV4TlpFiA+Uin
        jr8K/E3AT/T1GU3xOqeQ3J6baO1obLR8QCevQAW2lOL7i74KBAUimx0/izP8+Dhz
        aJPYMXtXnuocxUr715+GPst7JrGH7mUVJ9qb81ueaHq0Lm+WibP0B9O80azdZgUI
        y3kenOrYvltizYNQ4pZI3PK9ALR+YYPSaY7+bOhmycpD/XddkWOjatDa3NlfWJLU
        aAEJAhDXhU7RaEKYTAARe+9h8frjrL4Q9poPARFhDlZ9i6xefefBF8YVCDZGED6h
        FSW1EyDyY5lfEShAWjCL6QdLeTHCrstAez/4nKVoKsyjZabxGg/V17/rO2dZAmtk
        JpybHZPWD+lX
        =gpMP
        -----END PGP MESSAGE-----
      fp: 050787E6CDC4F90636141B1D2C5BB181A0326054
    - created_at: "2024-07-06T03:46:16Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hF4DHfhkqE7LHSASAQdAPAPxZ1K2CT6a/YoqGVIivop74cr2BBXuzpW6TMB4ewQw
        u0oBzCBYeKgeBy9P7xRNit3RbPJ36aTwAYrgOrt3QKIXjtl1Sp9DTUEOqGQwaEPi
        1GgBCQIQqwxElRPAw56vHLT0K/93F8EkUWUYeyg9C0KIK5kG+TguyzFXZ/KUpor6
        x7VtZvi+fBAIt8xWG3qyANJxDJQt2H6hJcYCGlXh7zRLXoNB1K+urTOS0bkePmcK
        VhzlQLeGOV6uQA==
        =dVCi
        -----END PGP MESSAGE-----
      fp: E39A9ADC5719F27F46267014C7339B5CD6A9FAB1
  encrypted_regex: ^(data|stringData)$
  version: 3.9.0
