---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: grafana-secrets
    creationPolicy: Owner
  data:
    - secretKey: TSIDP_CLIENT_ID
      remoteRef:
        key: grafana
        property: TSIDP_CLIENT_ID
    - secretKey: TSIDP_CLIENT_SECRET
      remoteRef:
        key: grafana
        property: TSIDP_CLIENT_SECRET
