version: '3'

tasks:
  deps:
    desc: Download playbooks from Ansible Galaxy
    dir: ansible
    cmds:
      - ansible-galaxy install --force --role-file requirements.yml

  ping:
    desc: Ping nodes in ansible inventory
    dir: ansible
    cmds:
      - ansible all -m ping

  play:
    desc: Run ansible playbook
    dir: ansible
    cmds:
      - ansible-playbook playbooks/{{.CLI_ARGS}}.yml

  k3s-restart:
    desc: Restart k3s everywhere
    dir: ansible
    cmds:
      - ansible all -m ansible.builtin.systemd -a "name=k3s state=restarted"
