version: '3'

tasks:
  deps:
    desc: Download playbooks from Ansible Galaxy
    dir: ansible
    cmds:
      - ansible-galaxy install --force --role-file requirements.yml

  ping:
    desc: Ping nodes in ansible inventory
    dir: ansible
    cmds:
      - ansible all -m ping

  k3s-install:
    desc: Install k3s
    deps: [deps]
    dir: ansible
    cmds:
      - ansible-playbook playbooks/k3s-install.yml

  k3s-restart:
    desc: Restart k3s everywhere
    dir: ansible
    cmds:
      - ansible all -m ansible.builtin.systemd -a "name=k3s state=restarted"

  k3s-nuke:
    desc: Nuke k3s everywhere
    dir: ansible
    cmds:
      - ansible-playbook playbooks/k3s-nuke.yml
