---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/litellm.home-operations.com/litellmproxy_v1alpha1.json
apiVersion: litellm.home-operations.com/v1alpha1
kind: LiteLLMProxy
metadata:
  name: litellm
spec:
  env:
    - name: DATABASE_URL
      valueFrom:
        secretKeyRef:
          name: litellm-db-app
          key: uri
    - name: LITELLM_MASTER_KEY
      valueFrom:
        secretKeyRef:
          name: litellm-secrets
          key: LITELLM_MASTER_KEY
  apiAccess:
    masterKeyRef:
      name: litellm-secrets
      key: LITELLM_MASTER_KEY
  routerSettings:
    redis_host: litellm-dragonfly
    redis_port: 6379
    retry_policy:
      RateLimitErrorRetries: 5
    allowed_fails: 10
    cooldown_time: 15
  route:
    hostnames:
      - litellm.bbck.dev
    parentRefs:
      - name: envoy-internal
        namespace: networking
