---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/litellm.home-operations.com/litellmmodel_v1alpha1.json
apiVersion: litellm.home-operations.com/v1alpha1
kind: LiteLLMModel
metadata:
  name: claude-opus
spec:
  modelName: claude-opus-*
  params:
    model: anthropic/claude-opus-*
    apiKeyRef:
      name: litellm-secrets
      key: ANTHROPIC_API_KEY
    dropParams: true
---
apiVersion: litellm.home-operations.com/v1alpha1
kind: LiteLLMModel
metadata:
  name: claude-sonnet
spec:
  modelName: claude-sonnet-*
  params:
    model: anthropic/claude-sonnet-*
    apiKeyRef:
      name: litellm-secrets
      key: ANTHROPIC_API_KEY
    dropParams: true
---
apiVersion: litellm.home-operations.com/v1alpha1
kind: LiteLLMModel
metadata:
  name: claude-haiku
spec:
  modelName: claude-haiku-*
  params:
    model: anthropic/claude-haiku-*
    apiKeyRef:
      name: litellm-secrets
      key: ANTHROPIC_API_KEY
    dropParams: true
---
apiVersion: litellm.home-operations.com/v1alpha1
kind: LiteLLMModel
metadata:
  name: voyage-4-lite
spec:
  modelName: voyage-4-lite
  params:
    model: voyage/voyage-4-lite
    apiKeyRef:
      name: litellm-secrets
      key: VOYAGE_API_KEY
    rpm: 3
    tpm: 10000
