---
originRequest:
  originServerName: external.bbck.dev

ingress:
  - hostname: "bbck.dev"
    service: https://ingress-nginx-external-controller.networking.svc.cluster.local:443
  - hostname: "*.bbck.dev"
    service: https://ingress-nginx-external-controller.networking.svc.cluster.local:443
  - service: http_status:404
