---
originRequest:
  originServerName: "external.${CLUSTER_DOMAIN}"

ingress:
  - hostname: "${CLUSTER_DOMAIN}"
    service: https://ingress-nginx-external-controller.networking.svc.cluster.local:443
  - hostname: "*.${CLUSTER_DOMAIN}"
    service: https://ingress-nginx-external-controller.networking.svc.cluster.local:443
  - service: http_status:404
