apiVersion: v1
kind: Service
metadata:
  annotations:
    tailscale.com/tailnet-fqdn: sabnzbd.taild1477.ts.net
  name: sabnzbd
  namespace: tailscale
spec:
  externalName: placeholder
  type: ExternalName
