grafana.ini:
  server:
    domain: homelab.bbck.net
    root_url: "%(protocol)s://%(domain)s/grafana"
    serve_from_sub_path: true
  auth.anonymous:
    enabled: true
    org_name: Main Org.
    org_role: Viewer
  analytics:
    check_for_updates: false
ingress:
  enabled: true
  hosts:
    - homelab.bbck.net
  path: /grafana
datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      url: http://prometheus-server
      access: proxy
      isDefault: true
      editable: false
dashboardProviders:
 dashboardproviders.yaml:
   apiVersion: 1
   providers:
   - name: 'default'
     orgId: 1
     folder: ''
     type: file
     disableDeletion: true
     editable: false
     options:
       path: /var/lib/grafana/dashboards/default
dashboards:
  default:
    flux-cluster:
      url: https://raw.githubusercontent.com/fluxcd/flux2/main/manifests/monitoring/grafana/dashboards/cluster.json
    flux-control-plane:
      url: https://raw.githubusercontent.com/fluxcd/flux2/main/manifests/monitoring/grafana/dashboards/control-plane.json
