---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/volsync.backube/replicationdestination_v1alpha1.json
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: "${APP}-r2"
spec:
  trigger:
    manual: restore-once
  restic:
    repository: "${APP}-volsync-r2"
    destinationPVC: "${APP}"
    copyMethod: Snapshot
    cacheStorageClassName: "${VOLSYNC_CACHE_SNAPSHOTCLASS:-openebs-zfspv}"
    storageClassName: "${VOLSYNC_STORAGECLASS:-openebs-zfspv}"
    volumeSnapshotClassName: "${VOLSYNC_SNAPSHOTCLASS:-openebs-zfspv}"
    moverSecurityContext:
      runAsUser: 65534
      runAsGroup: 65534
      fsGroup: 65534
