apiVersion: v1
kind: Secret
metadata:
  name: "${APP}-volsync-r2"
type: Opaque
stringData:
  RESTIC_REPOSITORY: ${RESTIC_REPOSITORY}/${APP}
  RESTIC_PASSWORD: ${RESTIC_PASSWORD}
  AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
  AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
