---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-nginx-external
spec:
  interval: 30m
  chart:
    spec:
      chart: ingress-nginx
      version: 4.13.3
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
  values:
    fullnameOverride: ingress-nginx-external
    controller:
      config:
        ssl-redirect: "true"
        force-ssl-redirect: "true"
      admissionWebhooks:
        objectSelector:
          matchExpressions:
            - key: ingress-class
              operator: In
              values: ["external"]
      replicaCount: 2
      extraArgs:
        default-ssl-certificate: networking/bbck-dev-tls
      service:
        type: LoadBalancer
        annotations:
          external-dns.alpha.kubernetes.io/hostname: external.bbck.dev
        externalTrafficPolicy: Local
      ingressClassResource:
        name: external
        default: false
        controllerValue: k8s.io/external
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
