---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: core
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./k8s/core
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client
