---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app overseerr
  namespace: flux-system
spec:
  targetNamespace: default
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./k8s/apps/default/overseerr/app
  dependsOn:
    - name: volsync
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  components:
    - ../../../../components/volsync
  postBuild:
    substitute:
      APP: *app
      APP_UID: "65534"
      APP_GID: "65534"
      VOLSYNC_CAPACITY: 1Gi
