clusterName: turingpi
talosVersion: v1.7.2-rk3588
endpoint: https://192.168.254.42:6443
cniConfig:
  name: none
nodes:
  - hostname: rk1-1
    ipAddress: 192.168.254.42
    installDisk: /dev/mmcblk0
    controlPlane: true
  - hostname: rk1-2
    ipAddress: 192.168.254.43
    installDisk: /dev/mmcblk0
    controlPlane: true
  - hostname: rk1-3
    ipAddress: 192.168.254.44
    installDisk: /dev/mmcblk0
    controlPlane: true
  - hostname: rk1-4
    ipAddress: 192.168.254.45
    installDisk: /dev/mmcblk0
controlPlane:
  talosImageURL: ghcr.io/nberlee/installer
  kernelModules: &kernelModules
    - name: rockchip-cpufreq
  patches:
    # Schedule on all nodes
    - |-
      cluster:
        allowSchedulingOnControlPlanes: true
    # Allow metric collection
    - |-
      cluster:
        controllerManager:
          extraArgs:
            bind-address: 0.0.0.0
        scheduler:
          extraArgs:
            bind-address: 0.0.0.0
        etcd:
          extraArgs:
            listen-metrics-urls: http://0.0.0.0:2381
    # Disable kube-proxy in favor of Cilium
    - &ciliumPatch |-
      cluster:
        proxy:
          disabled: true
    # NFS mount options
    - &nfsPatch |-
      machine:
        files:
          - op: overwrite
            path: /etc/nfsmount.conf
            permissions: 0o644
            content: |
              [ NFSMount_Global_Options ]
              nfsvers=4.2
              hard=True
              nconnect=8
worker:
  talosImageURL: ghcr.io/nberlee/installer
  kernelModules: *kernelModules
  patches:
    - *ciliumPatch
    - *nfsPatch
