clusterName: turingpi
talosVersion: v1.7.6
endpoint: https://192.168.254.41:6443
cniConfig:
  name: none
nodes:
  - hostname: rk1-1
    ipAddress: 192.168.254.41
    installDisk: /dev/nvme0n1
    controlPlane: true
    talosImageURL: ghcr.io/bbck/talos-rk1
    kernelModules:
      - name: rockchip-cpufreq
  - hostname: rk1-2
    ipAddress: 192.168.254.42
    installDisk: /dev/nvme0n1
    controlPlane: true
    talosImageURL: ghcr.io/bbck/talos-rk1
    kernelModules:
      - name: rockchip-cpufreq
  - hostname: rk1-3
    ipAddress: 192.168.254.43
    installDisk: /dev/nvme0n1
    controlPlane: true
    talosImageURL: ghcr.io/bbck/talos-rk1
    kernelModules:
      - name: rockchip-cpufreq
  - hostname: rk1-4
    ipAddress: 192.168.254.44
    installDisk: /dev/nvme0n1
    talosImageURL: ghcr.io/bbck/talos-rk1
    kernelModules:
      - name: rockchip-cpufreq
  - hostname: eq12
    ipAddress: 192.168.254.45
    installDisk: /dev/sda
    schematic:
      customization:
        systemExtensions:
          officialExtensions:
            - siderolabs/i915-ucode
            - siderolabs/iscsi-tools
            - siderolabs/tailscale
            - siderolabs/util-linux-tools
controlPlane:
  extensionServices: &extensionServices
    - name: tailscale
      environment:
        - TS_AUTHKEY=${TS_AUTHKEY}
  patches:
    # Schedule on all nodes
    - |-
      cluster:
        allowSchedulingOnControlPlanes: true
    # Allow metric collection
    - |-
      cluster:
        controllerManager:
          extraArgs:
            bind-address: 0.0.0.0
        scheduler:
          extraArgs:
            bind-address: 0.0.0.0
        etcd:
          extraArgs:
            listen-metrics-urls: http://0.0.0.0:2381
    # Enable kubelet certificate rotation for metrics-server
    - &metricsSererPatch |-
      machine:
        kubelet:
          extraArgs:
            rotate-server-certificates: true
    # Disable kube-proxy in favor of Cilium
    - &ciliumPatch |-
      cluster:
        proxy:
          disabled: true
    # NFS mount options
    - &nfsPatch |-
      machine:
        files:
          - op: overwrite
            path: /etc/nfsmount.conf
            permissions: 0o644
            content: |
              [ NFSMount_Global_Options ]
              nfsvers=4.2
              hard=True
              nconnect=8
worker:
  extensionServices: *extensionServices
  patches:
    - *metricsSererPatch
    - *ciliumPatch
    - *nfsPatch
