clusterName: turingpi
talosVersion: v1.9.0
endpoint: https://192.168.254.41:6443
cniConfig:
  name: none
nodes:
  - hostname: rk1-1
    ipAddress: 192.168.254.41
    installDisk: /dev/nvme0n1
    controlPlane: true
    schematic:
      overlay: &rk1
        image: siderolabs/sbc-rockchip
        name: turingrk1
      customization:
        systemExtensions:
          officialExtensions: &extensions
            - siderolabs/i915
            - siderolabs/iscsi-tools
            - siderolabs/util-linux-tools
  - hostname: rk1-2
    ipAddress: 192.168.254.42
    installDisk: /dev/nvme0n1
    controlPlane: true
    schematic:
      overlay: *rk1
      customization:
        systemExtensions:
          officialExtensions: *extensions
  - hostname: rk1-3
    ipAddress: 192.168.254.43
    installDisk: /dev/nvme0n1
    controlPlane: true
    schematic:
      overlay: *rk1
      customization:
        systemExtensions:
          officialExtensions: *extensions
  - hostname: rk1-4
    ipAddress: 192.168.254.44
    installDisk: /dev/nvme0n1
    schematic:
      overlay: *rk1
      customization:
        systemExtensions:
          officialExtensions: *extensions
  - hostname: eq12
    ipAddress: 192.168.254.45
    installDisk: /dev/sda
    nodeLabels:
      feature.node.kubernetes.io/2.5GbE: "true"
    schematic:
      customization:
        systemExtensions:
          officialExtensions: *extensions
controlPlane:
  patches:
    # Schedule on all nodes
    - |-
      cluster:
        allowSchedulingOnControlPlanes: true
    # Allow metric collection
    - |-
      cluster:
        controllerManager:
          extraArgs:
            bind-address: 0.0.0.0
        scheduler:
          extraArgs:
            bind-address: 0.0.0.0
        etcd:
          extraArgs:
            listen-metrics-urls: http://0.0.0.0:2381
    # Disable CoreDNS
    - |-
      cluster:
        coreDNS:
          disabled: true
    # Disable kube-proxy in favor of Cilium
    - |-
      cluster:
        proxy:
          disabled: true
    # Enable kubelet certificate rotation for metrics-server
    - &metricsSererPatch |-
      machine:
        kubelet:
          extraArgs:
            rotate-server-certificates: true
    # NFS mount options
    - &nfsPatch |-
      machine:
        files:
          - op: overwrite
            path: /etc/nfsmount.conf
            permissions: 0o644
            content: |
              [ NFSMount_Global_Options ]
              nfsvers=4.2
              hard=True
              nconnect=8
    - &longhornPatch |-
      machine:
        kubelet:
          extraMounts:
            - destination: /var/lib/longhorn
              type: bind
              source: /var/lib/longhorn
              options:
                - bind
                - rshared
                - rw
worker:
  patches:
    - *metricsSererPatch
    - *nfsPatch
    - *longhornPatch
