---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: alloy
  namespace: monitoring
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: alloy
  install:
    crds: CreateReplace
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    crds: CreateReplace
    remediation:
      retries: 3
  values:
    fullnameOverride: alloy
    alloy:
      configMap:
        create: false
        name: alloy
        key: config.alloy
    controller:
      # Collect logs from every node, including tainted ones like the NAS
      tolerations:
        - operator: Exists
          effect: NoSchedule
    configReloader:
      image:
        registry: ghcr.io
