apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tautulli
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 3.4.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 1m
  values:
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        runAsGroup: 65534
        fsGroup: 65534
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile:
          type: RuntimeDefault
    controllers:
      tautulli:
        replicas: 1
        containers:
          tautulli:
            image:
              repository: ghcr.io/tautulli/tautulli
              tag: "v2.14.5@sha256:9c3610497ec323dfcfbf6441509545903b9dc505d68797c3d4dbb3262591bcd8"
              pullPolicy: IfNotPresent
            command: python
            args:
              - "Tautulli.py"
              - "--datadir"
              - "/config"
            env:
              TZ: America/Los_Angeles
            resources:
              limits:
                memory: 512Mi
              requests:
                cpu: 100m
                memory: 256Mi
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /status
                    port: 8181
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
              startup:
                enabled: true
                spec:
                  periodSeconds: 5
                  failureThreshold: 30
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop: ["ALL"]
    service:
      tautulli:
        controller: tautulli
        ports:
          http:
            port: 8181
    # ingress:
    #   tautulli:
    #     className: tailscale
    #     hosts:
    #       - host: tautulli
    #         paths:
    #           - path: /
    #             service:
    #               identifier: tautulli
    #               port: http
    #     tls:
    #       - hosts:
    #           - tautulli
    persistence:
      config:
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 250Mi
        globalMounts:
          - path: /config
      cache:
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 1Gi
        globalMounts:
          - path: /config/cache
      logs:
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 250Mi
        globalMounts:
          - path: /config/logs
      tmp:
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 1Gi
        globalMounts:
          - path: /tmp
