---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: overseerr
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 3.4.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 1m
  values:
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        runAsGroup: 65534
        fsGroup: 65534
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile:
          type: RuntimeDefault
    controllers:
      overseerr:
        replicas: 1
        containers:
          overseerr:
            image:
              repository: ghcr.io/sct/overseerr
              tag: 1.33.2
              pullPolicy: IfNotPresent
            resources:
              limits:
                memory: 500Mi
              requests:
                cpu: 100m
                memory: 128Mi
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /api/v1/status
                    port: 5055
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
              startup:
                enabled: true
                spec:
                  periodSeconds: 5
                  failureThreshold: 30
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop: ["ALL"]
    service:
      overseerr:
        controller: overseerr
        ports:
          http:
            port: 5055
    ingress:
      overseerr:
        className: nginx
        hosts:
          - host: requests.${CLUSTER_DOMAIN}
            paths:
              - path: /
                service:
                  identifier: overseerr
                  port: http
        annotations:
          external-dns.alpha.kubernetes.io/target: nginx.${CLUSTER_DOMAIN}
    persistence:
      config:
        existingClaim: overseerr
        globalMounts:
          - path: /app/config
      cache:
        existingClaim: overseerr-cache
        globalMounts:
          - path: /app/config/cache
      logs:
        type: emptyDir
        globalMounts:
          - path: /app/config/logs
      tmp:
        type: emptyDir
