---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: "Terraform Plan"
on:
  pull_request:
    branches:
      - master
    paths:
      - "terraform/**"
jobs:
  changed-files:
    runs-on: [actions-runner]
    permissions:
      contents: read
    outputs:
      matrix: ${{ steps.changed-files.outputs.all_changed_files }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get changed terraform files
        id: changed-files
        uses: tj-actions/changed-files@e8772ff27de71367c2771ef3e8b5b2075b3f8282
        with:
          files: terraform/**
          dir_names: true
          dir_names_max_depth: 2
          matrix: true
      - name: List all changed terraform files
        run: echo '${{ steps.changed-files.outputs.all_changed_files }}'
  terraform-plan:
    runs-on: [actions-runner]
    needs: [changed-files]
    permissions:
      contents: read
      pull-requests: write
    strategy:
      matrix:
        files: ${{ fromJSON(needs.changed-files.outputs.matrix) }}
    steps:
      - name: Configure 1password
        uses: 1password/load-secrets-action/configure@v2
        with:
          connect-host: ${{ secrets.OP_CONNECT_HOST }}
          connect-token: ${{ secrets.OP_CONNECT_TOKEN }}
      - name: Load secrets
        uses: 1password/load-secrets-action@v2
        with:
          export-env: true
        env:
          AWS_ACCESS_KEY_ID: op://Homelab/terraform-bucket/username
          AWS_SECRET_ACCESS_KEY: op://Homelab/terraform-bucket/password
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install OpenTofu
        uses: opentofu/setup-opentofu@v1
        with:
          tofu_wrapper: false
      - name: OpenTofu fmt
        id: fmt
        run: tofu fmt -check
        working-directory: ${{ matrix.files }}
        continue-on-error: true
      - name: OpenTofu Init
        id: init
        run: tofu init
        working-directory: ${{ matrix.files }}
      - name: OpenTofu Plan
        id: plan
        run: tofu plan -no-color -var op_connect_token=${{ secrets.OP_CONNECT_TOKEN }} -out .planfile
        working-directory: ${{ matrix.files }}
        continue-on-error: true
      - name: Post PR comment
        uses: borchero/terraform-plan-comment@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          planfile: .planfile
          terraform-cmd: tofu
          working-directory: ${{ matrix.files }}
          header: 📝 Terraform Plan for ${{ matrix.files }}
