apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
  namespace: flux-system
type: Opaque
stringData:
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:g/4vQJeDsKywvEVKKp1RVwNgS2o4gWMOcfAV6V5n/U4M0LhljHyCk6Nh1X8nYIG6S2XsgQ+/DTUnSGsmApgENSwUgeXw2r7TOsLVFSV0MNQ=,iv:6ubItIKURiSXU0L42FTybnYTNu8LukB1thBBpReh0Qw=,tag:PHe6eXbcAtO0qz+ubcShoQ==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:tGbjnE4D87hSTvkU9A68MdGx2iMVjGVR9HxLPdZkc5xfinlL3bPbe8Nna+xeFTSsp9ihGs+EKv2detrXwt0U,iv:7cdW4/XaFEtaHiS8S08cLqOx6AAILmpAt4MaWkhG5uw=,tag:P/XOMubjP8QF7B4WWn3ofA==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:sLY5LzWQjrffDZ/PoBtJAhw3h3E0nJtYFBtfgSgZaJY=,iv:UllxCdUmIFDw29+5kF6dyT52F6DbLymvwTFK8CPzEsg=,tag:gfZCAXOJNc8QgA73wz8A4g==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:Pb+7cIYvpwKXSOMZUBsLMXEeF1yuWrE1Ks/bTyDXaOs1WNMMPCV+U9l7ibRfwDRdBQFdLCQ9gygv3kdHwDmmYA==,iv:ex8zj6biM0ekoa5hE4Blw4C+Zf1Q7n0MZO1hASF5Cf0=,tag:JbuMKzKgdXvqCFUK4TYbUw==,type:str]
  ACME_EMAIL: ENC[AES256_GCM,data:ewmu94e+1xOXdWn5BHLOUmBaXrI=,iv:Hw1PlNPmC5AEt3iQG6G3ILEDA0JfReWQUowr+Cx0C14=,tag:I5wA1QrF/5FHIKkR1cMswA==,type:str]
  NET_MONITORING_USER: ENC[AES256_GCM,data:A0O9dm8dCCoqjg==,iv:tkoQyUYcBKsU2dUMviYnBLemAgYn8J89z1P0wUS7xpU=,tag:C+jesOYpfAs2UwCl9AnBxQ==,type:str]
  NET_MONITORING_PASS: ENC[AES256_GCM,data:sQ+cWn0pWUUmTSpPksAhv4DwbiE=,iv:ZDKoVWd7JqjtpDN+zTUILJWrCAwlXpSpijXoypyi2G4=,tag:dERUvca+eJPsV0oEE21HtQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: "2024-10-20T04:19:15Z"
  mac: ENC[AES256_GCM,data:8xV+hNHQqjR+/1DZbx7zIm5p1FliSNMDR1GgRwWMlA3dgtWrakSAi+uKuXMc41MUmrGOQAHqlYtPx7CIOr4+3Gtg5WgJwiqAP81hHetNQ9TSH+X8Ew5JsyLfxOx4Wn2Qwqlz5INcApoEQqS22OBiTtvtoWrrux8lPUleOEmybis=,iv:uWUvcAdGpRiAVYatA+RybyRj3x32Kh7caEBMfTiHjjk=,tag:GKBi/r7zBAJDri+chgONkw==,type:str]
  pgp:
    - created_at: "2024-10-20T04:19:15Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA5DuDCLnNCw6ARAAsVqfd1rkkr85S/SehqXVRSkoFAhOuGhPe/ZPO9MEZTAy
        NDl3BPjNEmzmvUXaFqlPTyLeVedad4v4tCj+bP3lrtCpRek+5TbvRFGY6Sc6iu1a
        8Z+rKJJukdFlFmZxEZmwPRu1u2N2QrNOfdRq9hPoLFvPEcsP8JlyE+TZOoGi7OSq
        52kIBvA1Jy6FbBpvT1ZrAJT5A7B1WbXt0s6CQiM+D1J6+/28gYLIylbTt1gWR2Aa
        3NUhG/BOBVORoMS70YzrHt9RlUs/371+Qnqf1su7wmvkl2bD3bxf26joB1n3Qhy0
        deprjJgeF766VsUQrGllc+bt8lXHxfL3uM4FzaHs7BdublVgYVzh++sYmYK+q9NG
        qpMP9Eyq+uSA1Qn62SGC5VhCCTasj8najgHFYcpkwFSTj+00xx1BRICIrtve1soN
        Xyp8F28vukGOZmmbhKCdzPvWcSpzNnQeDHa8+z+L755cAEX5aVzd0LWErUnHKdr5
        /A7gkSjbINCNNE+froDn/ecVKaTPdiR9epN3LJQ3zifJDJ8La68SIT7DmYznWaQF
        iDTcKWCpqJ8GHmKiVAVj/I/+fJMWT493C+uVPa0tDROSu8Br3DPy3qqMATP7W2Py
        mrtE5TUvykbVWBfCYU/Hrut5NPzGnhIdhoxu/P9Oz8QTGjYypheQZ2ZEzBfzWwvU
        aAEJAhBLxZcujqhCueZZzjOgZdx2vIjc1N40+vO2q5s9RxyZfrqCbOkzHRKNB92U
        z2/7ccVk9FcY5ndyQYF4mcIwFUnEdC4IhdB3VPD/T9xAJz6tOd6rbJkf5z/S5BXe
        msQIZMZIgObi
        =fJ/4
        -----END PGP MESSAGE-----
      fp: 050787E6CDC4F90636141B1D2C5BB181A0326054
    - created_at: "2024-10-20T04:19:15Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hF4DHfhkqE7LHSASAQdAuSwR+IZ7Nk5xAsB/he+OsZAPQd9m9abax0J0/6riMQsw
        JmIWRN/Ekc4+0c6wsm+s2khAHdvnZYckbpDSSPKM90viGoArbtEXvEP7vzwLigwN
        1GgBCQIQ6u9eYiBVlJ3fxT+H5bT5qK+Cyf1ER5zlCc1GcNwcZ1pBzmh6BeZfMD+H
        SJjE4HxjlkP6vHIWUNzXQE/mF8o+2l164zugbjYfpA4s4mKLbuqwJKW9Bbox9v59
        Q7oo9KT9Ubj4vw==
        =xfjd
        -----END PGP MESSAGE-----
      fp: E39A9ADC5719F27F46267014C7339B5CD6A9FAB1
  encrypted_regex: ^(data|stringData)$
  version: 3.9.1
